In [16]:
import tensorflow as tf
import numpy as np

In [17]:
tf.enable_eager_execution()
print(tf.__version__)

1.15.0


In [96]:
x = tf.constant(3.0)
with tf.GradientTape() as t:
    t.watch(x)
    y = x * x
    z = y * y
dz_dx = t.gradient(z, x)    # 108.0 (4*x^3 at x = 3)
dy_dx = t.gradient(y, x)    # 6.0
#del t    # 테이프에 대한 참조를 드롭합니다.

RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.

In [42]:
dz_dx

In [43]:
dy_dx

In [31]:
x = tf.constant(2.0)
dz_dx = t.gradient(z, x)    # 108.0 (4*x^3 at x = 3)
dy_dx = t.gradient(y, x)    # 6.0

In [86]:
x = tf.Variable([[9.0]])
with tf.GradientTape() as t2:
    y = x * x

dy_dx = t2.gradient(y, x)    # 6.0
dy_dx
#del t    # 테이프에 대한 참조를 드롭합니다.

<tf.Tensor: id=445, shape=(1, 1), dtype=float32, numpy=array([[18.]], dtype=float32)>

In [89]:
w = tf.Variable([[5.0]])
with tf.GradientTape() as tape:
    loss = w * w

grad = tape.gradient(loss, w)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)


RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.

In [92]:
w = tf.Variable([[5.0]])
loss = w * w
grad = tape.gradient(loss, w)

RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.

In [93]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = w * w

grad = tape.gradient(loss, w)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [94]:
grad = tape.gradient(loss, w)

RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.