In [38]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [39]:
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
],dtype = "float32")

In [40]:
y = np.array([
    [0.],
    [0.],
    [0.],
    [1.]
], dtype="float32")

In [41]:
w = np.array([2,3], dtype="float32")
b = np.array([4,5], dtype="float32")

In [42]:
X*w+b

array([[4., 5.],
       [4., 8.],
       [6., 5.],
       [6., 8.]], dtype=float32)

np.exp() ; 자연상수의 지수승

$np.exp(-h) == e^{-h}$

In [43]:
def sigmoid(h):
    return 1/ (1 + np.exp(-h))

In [44]:
hypothesis = sigmoid(X*w+b)
hypothesis

array([[0.98201376, 0.9933072 ],
       [0.98201376, 0.99966466],
       [0.9975274 , 0.9933072 ],
       [0.9975274 , 0.99966466]], dtype=float32)

In [45]:
hypothesis.T[0]

array([0.98201376, 0.98201376, 0.9975274 , 0.9975274 ], dtype=float32)

In [46]:
y.T[0]

array([0., 0., 0., 1.], dtype=float32)

In [47]:
X.T[0]

array([0., 0., 1., 1.], dtype=float32)

In [48]:
w1_gred = 1/8 * np.sum(np.dot((hypothesis.T[0] - y.T), X.T[0]))
print("w_gred: ", w1_gred)

w_gred:  0.12438185513019562


In [49]:
w2_gred = 1/8 * np.sum(np.dot((hypothesis.T[1] - y.T), X.T[1]))
print("w_gred: ", w2_gred)

w_gred:  0.12491616606712341


In [50]:
b1_gred = 1/8 * np.sum(hypothesis[0]-y)
print('b1-gred: ', b1_gred)

b1-gred:  0.7376604676246643


In [51]:
b2_gred = 1/8 * np.sum(hypothesis[1]-y)
print('b2_gred: ', b2_gred)

b2_gred:  0.7408392429351807


In [52]:
learning_rate = 0.1

for i in range(100):
    for i in range(2):
        hypothesis = sigmoid(X*w+b)
        print('hypothesis: ', hypothesis)
        cost = -tf.reduce_mean(y * tf.log(1 - hypothesis) + (1 - y) * tf.log(1 - hypothesis))
        print('cost: ', cost)
        
        w_gred = 1/8 * np.sum(np.dot((hypothesis.T[i]-y.T), X.T[i]))
        print(f'w{i}_gred: {w_gred}')
        w[i] = w[i] - learning_rate * w_gred
        print(f'w{i} : {w}')
        b_gred = 1/8 * np.sum(hypothesis[i]-y)
        print(f'b{i}_gred: {b_gred}')
        b[i] = b[i] - learning_rate * b_gred
        print(f'b{i} : {b}')

hypothesis:  [[0.98201376 0.9933072 ]
 [0.98201376 0.99966466]
 [0.9975274  0.9933072 ]
 [0.9975274  0.99966466]]
cost:  tf.Tensor(5.7569346, shape=(), dtype=float32)
w0_gred: 0.12438185513019562
w0 : [1.9875618 3.       ]
b0_gred: 0.7376604676246643
b0 : [3.926234 5.      ]
hypothesis:  [[0.9806635  0.9933072 ]
 [0.9806635  0.99966466]
 [0.9973054  0.9933072 ]
 [0.9973054  0.99966466]]
cost:  tf.Tensor(5.71734, shape=(), dtype=float32)
w1_gred: 0.12491616606712341
w1 : [1.9875618 2.9875083]
b1_gred: 0.740164041519165
b1 : [3.926234  4.9259834]
hypothesis:  [[0.9806635 0.9927967]
 [0.9806635 0.9996344]
 [0.9973054 0.9927967]
 [0.9973054 0.9996344]]
cost:  tf.Tensor(5.677353, shape=(), dtype=float32)
w0_gred: 0.12432634830474854
w0 : [1.9751291 2.9875083]
b0_gred: 0.7367300987243652
b0 : [3.852561  4.9259834]
hypothesis:  [[0.9792158 0.9927967]
 [0.9792158 0.9996344]
 [0.9970638 0.9927967]
 [0.9970638 0.9996344]]
cost:  tf.Tensor(5.637839, shape=(), dtype=float32)
w1_gred: 0.12490859627

w0_gred: 0.11713026463985443
w0 : [1.6095126 2.61372  ]
b0_gred: 0.6501050591468811
b0 : [1.7402143 2.7771115]
hypothesis:  [[0.8507143 0.9414264]
 [0.8507143 0.9954625]
 [0.9660959 0.9414264]
 [0.9660959 0.9954625]]
cost:  tf.Tensor(3.3797398, shape=(), dtype=float32)
w1_gred: 0.12386561930179596
w1 : [1.6095126 2.6013334]
b1_gred: 0.6730884313583374
b1 : [1.7402143 2.7098026]
hypothesis:  [[0.8507143  0.93760264]
 [0.8507143  0.9950879 ]
 [0.9660959  0.93760264]
 [0.9660959  0.9950879 ]]
cost:  tf.Tensor(3.344101, shape=(), dtype=float32)
w0_gred: 0.11652398109436035
w0 : [1.5978602 2.6013334]
b0_gred: 0.6441584825515747
b0 : [1.6757985 2.7098026]
hypothesis:  [[0.8423474  0.93760264]
 [0.8423474  0.9950879 ]
 [0.963514   0.93760264]
 [0.963514   0.9950879 ]]
cost:  tf.Tensor(3.3121192, shape=(), dtype=float32)
w1_gred: 0.12377198040485382
w1 : [1.5978602 2.588956 ]
b1_gred: 0.668717622756958
b1 : [1.6757985 2.642931 ]
hypothesis:  [[0.8423474  0.9335739 ]
 [0.8423474  0.99468493]
 [

cost:  tf.Tensor(1.6626108, shape=(), dtype=float32)
w0_gred: 0.0746321827173233
w0 : [1.2833592 2.2160788]
b0_gred: 0.36065948009490967
b0 : [0.05023579 0.84614086]
hypothesis:  [[0.5125563  0.699757  ]
 [0.5125563  0.9553072 ]
 [0.79143465 0.699757  ]
 [0.79143465 0.9553072 ]]
cost:  tf.Tensor(1.6492972, shape=(), dtype=float32)
w1_gred: 0.11382679641246796
w1 : [1.2833592 2.2046962]
b1_gred: 0.4839317798614502
b1 : [0.05023579 0.7977477 ]
hypothesis:  [[0.5125563  0.68949246]
 [0.5125563  0.9526844 ]
 [0.79143465 0.68949246]
 [0.79143465 0.9526844 ]]
cost:  tf.Tensor(1.6266364, shape=(), dtype=float32)
w0_gred: 0.07285866141319275
w0 : [1.2760733 2.2046962]
b0_gred: 0.3510243892669678
b0 : [0.01513335 0.7977477 ]
hypothesis:  [[0.5037833  0.68949246]
 [0.5037833  0.9526844 ]
 [0.78435135 0.68949246]
 [0.78435135 0.9526844 ]]
cost:  tf.Tensor(1.6138275, shape=(), dtype=float32)
w1_gred: 0.11317110061645508
w1 : [1.2760733 2.1933792]
b1_gred: 0.47823381423950195
b1 : [0.01513335 0.749

cost:  tf.Tensor(0.8535764, shape=(), dtype=float32)
w1_gred: 0.07450529932975769
w1 : [1.1217353 1.8768988]
b1_gred: 0.3167235851287842
b1 : [-0.68374515 -0.5420495 ]
hypothesis:  [[0.3354259  0.36771095]
 [0.3354259  0.7916416 ]
 [0.60778004 0.36771095]
 [0.60778004 0.7916416 ]]
cost:  tf.Tensor(0.84286135, shape=(), dtype=float32)
w0_gred: 0.02694500982761383
w0 : [1.1190408 1.8768988]
b0_gred: 0.10156843811273575
b0 : [-0.693902  -0.5420495]
hypothesis:  [[0.33316562 0.36771095]
 [0.33316562 0.7916416 ]
 [0.60471225 0.36771095]
 [0.60471225 0.7916416 ]]
cost:  tf.Tensor(0.84006476, shape=(), dtype=float32)
w1_gred: 0.07291039824485779
w1 : [1.1190408 1.8696077]
b1_gred: 0.3124036192893982
b1 : [-0.693902  -0.5732899]


In [64]:
w.dot(X) + b

ValueError: shapes (2,4) and (2,) not aligned: 4 (dim 1) != 2 (dim 0)

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

tf.enable_eager_execution()
tf.__version__

'1.15.0'

In [2]:
# 독립변수 X, 종속변수 Y
X = [1, 2, 3]
Y = [3, 5, 7]

In [9]:
# tf.random_normal 로 난수생성
# tf.random_normal(생성할 난수의 형식(1개의 데이터가 저장된 배열), 평균, 표준편차)
W = tf.Variable(tf.random_normal([1], 0., 1.))
b = tf.Variable(tf.random_normal([1], 0., 1.))

In [10]:
W.numpy()

array([0.54092294], dtype=float32)

In [11]:
learning_rate = 0.1

In [14]:
# 300번 반복해서 W, b 업데이트
for i in range(300):
    # with == (open, close)
    with tf.GradientTape() as tape:
        hypothesis = W * X + b
        print("hypothesis:",hypothesis)
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
        print('cost:',cost)
    W_grad, b_grad = tape.gradient(cost, [W, b])
    print('W_grad:', W_grad, ":b_grad:", b_grad)
    # W,b 값을 감소
    W.assign_sub(W_grad*learning_rate)
    b.assign_sub(b_grad*learning_rate)

hypothesis: tf.Tensor([1.8984411 4.470694  7.042947 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.4984804, shape=(), dtype=float32)
W_grad: tf.Tensor([-1.3542203], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.0586121], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.1397243 4.847399  7.555074 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.35715625, shape=(), dtype=float32)
W_grad: tf.Tensor([0.3331635], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.3052016], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.136928  4.811287  7.4856453], shape=(3,), dtype=float32)
cost: tf.Tensor(0.33878574, shape=(), dtype=float32)
W_grad: tf.Tensor([0.14429194], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.37742645], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.1602416 4.8201714 7.480101 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.3226765, shape=(), dtype=float32)
W_grad: tf.Tensor([0.16059172], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.3596573], shape=(1,), d

cost: tf.Tensor(0.05596214, shape=(), dtype=float32)
W_grad: tf.Tensor([0.06604913], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.15014443], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.6585839 4.9267325 7.1948814], shape=(3,), dtype=float32)
cost: tf.Tensor(0.053303957, shape=(), dtype=float32)
W_grad: tf.Tensor([0.06446218], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.14653477], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.6667912 4.928494  7.1901965], shape=(3,), dtype=float32)
cost: tf.Tensor(0.050771978, shape=(), dtype=float32)
W_grad: tf.Tensor([0.06291246], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.14301223], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.6748013 4.9302125 7.185624 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.04836026, shape=(), dtype=float32)
W_grad: tf.Tensor([0.06139913], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.13957469], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.6826189 4.93189   7.1811614], shape

hypothesis: tf.Tensor([2.8741045 4.972983  7.0718613], shape=(3,), dtype=float32)
cost: tf.Tensor(0.0072478815, shape=(), dtype=float32)
W_grad: tf.Tensor([0.02376938], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.05403424], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.877131 4.973632 7.070133], shape=(3,), dtype=float32)
cost: tf.Tensor(0.00690358, shape=(), dtype=float32)
W_grad: tf.Tensor([0.02319621], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.05273597], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.880085  4.9742665 7.068448 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.006575653, shape=(), dtype=float32)
W_grad: tf.Tensor([0.02264149], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.05146695], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.8829675 4.9748845 7.066802 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.006263303, shape=(), dtype=float32)
W_grad: tf.Tensor([0.02209504], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.05023067], shape=

hypothesis: tf.Tensor([2.955782  4.990511  7.0252395], shape=(3,), dtype=float32)
cost: tf.Tensor(0.0008941034, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00834815], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.01897844], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9568453 4.9907393 7.0246334], shape=(3,), dtype=float32)
cost: tf.Tensor(0.00085163134, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00814946], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.01852131], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9578824 4.9909616 7.0240407], shape=(3,), dtype=float32)
cost: tf.Tensor(0.00081118016, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00795174], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.0180769], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.958895  4.991179  7.0234632], shape=(3,), dtype=float32)
cost: tf.Tensor(0.0007726527, shape=(), dtype=float32)
W_grad: tf.Tensor([0.0077618], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.01764186],

hypothesis: tf.Tensor([2.985207  4.9968257 7.008444 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.00010006832, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00279331], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00634893], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9855628 4.9969015 7.00824  ], shape=(3,), dtype=float32)
cost: tf.Tensor(9.531153e-05, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00272433], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00619698], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.98591   4.9969764 7.008043 ], shape=(3,), dtype=float32)
cost: tf.Tensor(9.0786314e-05, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00266075], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00604725], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9862485 4.997049  7.007849 ], shape=(3,), dtype=float32)
cost: tf.Tensor(8.6474465e-05, shape=(), dtype=float32)
W_grad: tf.Tensor([0.0025959], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00590229

hypothesis: tf.Tensor([2.9946766 4.9988575 7.0030384], shape=(3,), dtype=float32)
cost: tf.Tensor(1.295864e-05, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00100454], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.002285], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9948046 4.998885  7.0029655], shape=(3,), dtype=float32)
cost: tf.Tensor(1.2342913e-05, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00098085], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00222985], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9949296 4.9989123 7.002895 ], shape=(3,), dtype=float32)
cost: tf.Tensor(1.1757594e-05, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00095924], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00217549], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9950514 4.998938  7.002825 ], shape=(3,), dtype=float32)
cost: tf.Tensor(1.1198623e-05, shape=(), dtype=float32)
W_grad: tf.Tensor([0.0009346], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00212383],

W_grad: tf.Tensor([0.0004406], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.0009985], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9977283 4.9995127 7.0012965], shape=(3,), dtype=float32)
cost: tf.Tensor(2.3596187e-06, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00042884], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00097497], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.997783 4.999524 7.001265], shape=(3,), dtype=float32)
cost: tf.Tensor(2.2473814e-06, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00041755], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00095193], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9978366 4.999536  7.0012355], shape=(3,), dtype=float32)
cost: tf.Tensor(2.1406759e-06, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00041008], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00092793], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([2.9978883 4.9995465 7.001205 ], shape=(3,), dtype=float32)
cost: tf.Tensor(2.038916e-06,