In [1]:
import numpy as np
import time

In [2]:
X = np.array([1,2,3], dtype='float32')
X

array([1., 2., 3.], dtype=float32)

In [3]:
y = np.array([2,2.5, 3.5], dtype="float32")
y

array([2. , 2.5, 3.5], dtype=float32)

In [4]:
# 임의의 w, b 정함
w = 2
b = 1
learning_rate = 0.1

In [5]:
hypothesis = w * X + b
hypothesis

array([3., 5., 7.], dtype=float32)

In [6]:
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import animation

# First set up the figure, the axis, and the plot element we want to animate
fig = plt.figure()
ax = plt.axes(xlim=(.5, 3.5), ylim=(0, 5))
# 예측데이터
line, = ax.plot([], [], lw=2)
# 원본데이터
line2, = ax.plot([], [], lw=2)

# initialization function: plot the background of each frame
def init():
    line.set_data([], [])
    return line, line2

# animation function.  This is called sequentially
def animate(i):
    global w, b, learning_rate
    hypothesis = w * X + b
    MSE = np.sum((hypothesis-y)**2)
    w_gred = 1/3*np.dot((hypothesis-y), X.T)
    b_gred = 1/3 * np.sum(hypothesis-y)
    w = w - (learning_rate*w_gred)
    b = b - (learning_rate*b_gred)
    line.set_data(X, hypothesis)
    line2.set_data(X, y)
    return line, line2

# call the animator.  blit=True means only re-draw the parts that have changed.
anim = animation.FuncAnimation(fig, animate, init_func=init, frames=200, interval=20, blit=True)

anim.save('exAnimation.gif', writer='pillow', fps=30, dpi=100)

plt.show()

<Figure size 640x480 with 1 Axes>

In [7]:
learning_rate = 0.1

%matplotlib inline
for i in range(200):
    # 예측값
    hypothesis = w * X + b
    print('hypothesis : ', hypothesis)
    # (예측값-진짜값) 의 제곱 합
    MSE = np.sum((hypothesis-y)**2)
    print('MSE : ', MSE)
    w_gred = 1/3*np.dot((hypothesis-y), X.T)
    print('w_gred : ', w_gred)
    b_gred = 1/3 * np.sum(hypothesis-y)
    print('b_gred : ', b_gred)
    # 업데이트
    w = w - (learning_rate*w_gred)
    print('w : ', w)
    b = b - (learning_rate*b_gred)
    print('b : ', b)

hypothesis :  [1.8867207 2.6602404 3.4337602]
MSE :  0.04289691
w_gred :  0.002827326456705729
b_gred :  -0.0064262549082438145
w :  0.7732369979222621
b :  1.113843472798666
hypothesis :  [1.8870804 2.6603174 3.4335544]
MSE :  0.042867523
w_gred :  0.002792835235595703
b_gred :  -0.00634924570719401
w :  0.7729577143987025
b :  1.1144783973693853
hypothesis :  [1.8874362 2.6603937 3.4333515]
MSE :  0.042838786
w_gred :  0.0027593771616617837
b_gred :  -0.00627287228902181
w :  0.7726817766825363
b :  1.1151056845982874
hypothesis :  [1.8877873 2.660469  3.433151 ]
MSE :  0.042810787
w_gred :  0.002726157506306966
b_gred :  -0.006197532018025716
w :  0.7724091609319057
b :  1.11572543780009
hypothesis :  [1.8881345 2.6605437 3.432953 ]
MSE :  0.042783484
w_gred :  0.002693494160970052
b_gred :  -0.006122986475626627
w :  0.7721398115158087
b :  1.1163377364476528
hypothesis :  [1.8884776 2.6606174 3.4327571]
MSE :  0.04275679
w_gred :  0.0026612281799316406
b_gred :  -0.006049315134684

MSE :  0.04173421
w_gred :  0.0006624857584635416
b_gred :  -0.001505772272745768
w :  0.7554447372754419
b :  1.1542895038922634
hypothesis :  [1.9097342 2.665179  3.4206238]
MSE :  0.041732594
w_gred :  0.0006545384724934895
b_gred :  -0.0014876524607340493
w :  0.7553792834281926
b :  1.1544382691383368
hypothesis :  [1.9098175 2.665197  3.420576 ]
MSE :  0.041731063
w_gred :  0.0006465117136637369
b_gred :  -0.0014698505401611328
w :  0.7553146322568263
b :  1.154585254192353
hypothesis :  [1.9099    2.6652145 3.4205294]
MSE :  0.041729447
w_gred :  0.000639041264851888
b_gred :  -0.001452048619588216
w :  0.7552507281303411
b :  1.1547304590543117
hypothesis :  [1.9099813 2.665232  3.4204826]
MSE :  0.04172798
w_gred :  0.0006310145060221354
b_gred :  -0.0014347235361735025
w :  0.7551876266797389
b :  1.154873931407929
hypothesis :  [1.9100616 2.6652493 3.4204369]
MSE :  0.041726556
w_gred :  0.0006236235300699869
b_gred :  -0.001417398452758789
w :  0.7551252643267319
b :  1.155