## tensorflow 사용

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

tf.enable_eager_execution()
tf.__version__

'1.15.0'

In [2]:
# 독립변수 X, 종속변수 Y
X = [1, 2, 3]
Y = [2,2.5, 3.5]

In [3]:
# tf.random_normal 로 난수생성
# tf.random_normal(생성할 난수의 형식(1개의 데이터가 저장된 배열), 평균, 표준편차)
W = tf.Variable(tf.random_normal([1], 0., 1.))
b = tf.Variable(tf.random_normal([1], 0., 1.))

In [4]:
W

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.51163644], dtype=float32)>

In [5]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-1.6755207], dtype=float32)>

In [6]:
W.numpy()

array([-0.51163644], dtype=float32)

In [7]:
learning_rate = 0.1

In [8]:
# 300번 반복해서 W, b 업데이트
for i in range(300):
    # with == (open, close)
    with tf.GradientTape() as tape:
        hypothesis = W * X + b
        print("hypothesis:",hypothesis)
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
        print('cost:',cost)
    W_grad, b_grad = tape.gradient(cost, [W, b])
    print('W_grad:', W_grad, ":b_grad:", b_grad)
    # W,b 값을 감소
    W.assign_sub(W_grad*learning_rate)
    b.assign_sub(b_grad*learning_rate)
    print('W: ',W)
    print('b: ',b)
    print('='*50)

hypothesis: tf.Tensor([-2.1871572 -2.6987934 -3.21043  ], shape=(3,), dtype=float32)
cost: tf.Tensor(29.863205, shape=(), dtype=float32)
W_grad: tf.Tensor([-23.144024], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-10.730921], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.8027658], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.60242856], dtype=float32)>
hypothesis: tf.Tensor([1.2003373 3.0031033 4.805869 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.8659558, shape=(), dtype=float32)
W_grad: tf.Tensor([2.749434], shape=(1,), dtype=float32) :b_grad: tf.Tensor([0.67287314], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.5278225], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.6697159], dtype=float32)>
hypothesis: tf.Tensor([0.8581066 2.385929  3.9137516], shape=(3,), dtype=float32)
cost: tf.Tensor(0.49

W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0843945], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.4065094], dtype=float32)>
hypothesis: tf.Tensor([1.4909039 2.5752983 3.6596928], shape=(3,), dtype=float32)
cost: tf.Tensor(0.0967835, shape=(), dtype=float32)
W_grad: tf.Tensor([0.08038585], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.1827367], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0763558], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.42478308], dtype=float32)>
hypothesis: tf.Tensor([1.5011389 2.5774946 3.6538503], shape=(3,), dtype=float32)
cost: tf.Tensor(0.09284591, shape=(), dtype=float32)
W_grad: tf.Tensor([0.07845274], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.17834412], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0685105], dtype=float32)>
b:  <t

W_grad: tf.Tensor([0.04375108], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.09945662], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.92762315], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.76288754], dtype=float32)>
hypothesis: tf.Tensor([1.6905107 2.6181338 3.5457568], shape=(3,), dtype=float32)
cost: tf.Tensor(0.037277628, shape=(), dtype=float32)
W_grad: tf.Tensor([0.04269917], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.09706577], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.92335325], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.7725941], dtype=float32)>
hypothesis: tf.Tensor([1.6959474 2.6193006 3.542654 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.03616666, shape=(), dtype=float32)
W_grad: tf.Tensor([0.04167382], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.09473196], shape

hypothesis: tf.Tensor([1.7842572 2.6382518 3.4922462], shape=(3,), dtype=float32)
cost: tf.Tensor(0.021906214, shape=(), dtype=float32)
W_grad: tf.Tensor([0.02499945], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.05682993], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.8514946], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.9359456], dtype=float32)>
hypothesis: tf.Tensor([1.7874402 2.6389349 3.4904294], shape=(3,), dtype=float32)
cost: tf.Tensor(0.021525389, shape=(), dtype=float32)
W_grad: tf.Tensor([0.02439871], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.05546372], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.84905475], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.94149196], dtype=float32)>
hypothesis: tf.Tensor([1.7905467 2.6396015 3.488656 ], shape=(3,), dtype=float32)
cost: tf.Tensor(

W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.80942297], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0315843], dtype=float32)>
hypothesis: tf.Tensor([1.8410072 2.6504302 3.4598532], shape=(3,), dtype=float32)
cost: tf.Tensor(0.016506573, shape=(), dtype=float32)
W_grad: tf.Tensor([0.01428477], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.03247293], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.8079945], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0348315], dtype=float32)>
hypothesis: tf.Tensor([1.842826  2.6508205 3.458815 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.016382227, shape=(), dtype=float32)
W_grad: tf.Tensor([0.01394153], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.03169227], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.80660033], dtype=float32)>
b

W_grad: tf.Tensor([0.00796682], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.01810885], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.78234166], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0931464], dtype=float32)>
hypothesis: tf.Tensor([1.875488  2.6578298 3.4401712], shape=(3,), dtype=float32)
cost: tf.Tensor(0.014664314, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00777418], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.01767398], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.78156424], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0949138], dtype=float32)>
hypothesis: tf.Tensor([1.8764781 2.6580424 3.4396067], shape=(3,), dtype=float32)
cost: tf.Tensor(0.014627476, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00758862], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.01724855], shape

cost: tf.Tensor(0.014244821, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00526747], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.01197417], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.77138513], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1180533], dtype=float32)>
hypothesis: tf.Tensor([1.8894384 2.6608236 3.4322085], shape=(3,), dtype=float32)
cost: tf.Tensor(0.014227926, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00514078], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.01168633], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.77087104], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1192219], dtype=float32)>
hypothesis: tf.Tensor([1.890093 2.660964 3.431835], shape=(3,), dtype=float32)
cost: tf.Tensor(0.014211815, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00501719], shape=(1,), dty

hypothesis: tf.Tensor([1.9007251 2.6632457 3.4257662], shape=(3,), dtype=float32)
cost: tf.Tensor(0.014005102, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00301011], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00684198], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.76221955], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1388887], dtype=float32)>
hypothesis: tf.Tensor([1.9011083 2.6633277 3.4255476], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013999558, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00293764], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00667763], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.76192576], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1395565], dtype=float32)>
hypothesis: tf.Tensor([1.9014823 2.663408  3.425334 ], shape=(3,), dtype=float32)
cost: tf.Tensor(

hypothesis: tf.Tensor([1.9077766 2.664759  3.421741 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013925042, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00167832], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00381565], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.7568144], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.151176], dtype=float32)>
hypothesis: tf.Tensor([1.9079905 2.664805  3.4216192], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013923326, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00163856], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00372363], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.75665057], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1515484], dtype=float32)>
hypothesis: tf.Tensor([1.908199  2.6648495 3.4215002], shape=(3,), dtype=float32)
cost: tf.Tensor(0.

hypothesis: tf.Tensor([1.911709  2.6656027 3.4194963], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013900135, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00093548], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00212804], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.7538002], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.158028], dtype=float32)>
hypothesis: tf.Tensor([1.9118283 2.6656284 3.4194288], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013899581, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00091442], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00207631], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.7537088], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1582357], dtype=float32)>
hypothesis: tf.Tensor([1.9119444 2.6656532 3.419362 ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.0

cost: tf.Tensor(0.013892385, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00052199], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00118668], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.7521193], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1618489], dtype=float32)>
hypothesis: tf.Tensor([1.9139682 2.6660876 3.4182067], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013892238, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00050902], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00115832], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.7520684], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1619648], dtype=float32)>
hypothesis: tf.Tensor([1.9140332 2.6661015 3.41817  ], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013892047, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00049734], shape=(1,), dt

W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.7513027], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1637052], dtype=float32)>
hypothesis: tf.Tensor([1.915008  2.6663108 3.4176135], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013890154, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00031337], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00071184], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.75127137], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1637764], dtype=float32)>
hypothesis: tf.Tensor([1.9150478 2.6663191 3.4175906], shape=(3,), dtype=float32)
cost: tf.Tensor(0.01389008, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00030525], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00069499], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.75124085], dtype=float32)>
b:

b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1649745], dtype=float32)>
hypothesis: tf.Tensor([1.9157188 2.6664634 3.4172077], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013889313, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00017914], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00040674], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.75072646], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1650151], dtype=float32)>
hypothesis: tf.Tensor([1.9157416 2.6664681 3.4171944], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013889301, shape=(), dtype=float32)
W_grad: tf.Tensor([0.00017397], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-0.00039728], shape=(1,), dtype=float32)
W:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.75070906], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1650548], dtype=float32)>
h

In [9]:
W.numpy()

array([0.7505696], dtype=float32)

In [10]:
W*X+b

<tf.Tensor: id=12938, shape=(3,), dtype=float32, numpy=array([1.9159415, 2.666511 , 3.4170806], dtype=float32)>