In [1]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import numpy as np

Using TensorFlow backend.


In [2]:
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
], dtype = 'float32')

y = np.array([0,0,0,1], dtype = 'int32')

In [3]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
y

array([0, 0, 0, 1])

In [38]:
model = Sequential()

# Dense(1, input_dim=2, activation='sigmoid')
# Dense : 선형회귀 수행 객체
# Dense(출력데이터의 칸의수, input_dim, activation) 
# 출력데이터의 칸의수 : 출력 데이터는 y이고 칸의 수는 1
# input_dim : 입력 데이터의 칸의 수, x이고 칸의 수는 2
# activation : 선형회귀 후 sigmoid 함수를 활성 함수를 이용해 0~1 사이 값 리턴

# Dense 모델을 예측 할 수 있도록 model에 추가
model.add(Dense(1, input_dim=2, activation='sigmoid'))

In [39]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [8]:
# GradientDecent를 이용해서 W와 b를 찾는 방법을 설정함
# loss='binary_crossentropy : -1/4 * (y * np.log(hypothesis) + (1 - y) * np.log(1- hypothesis))
# 합이 최소가 되는 W와 b를 찾음
# optimizer=Adam(lr=0.1) : learning rate를 0.1
# compile : 학습시킬 환경설정
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc'])

In [9]:
model.fit(X, y, epochs=100)




Epoch 1/100





4/4 [==============================] - 0s 72ms/step - loss: 0.6980 - acc: 0.5000
Epoch 2/100
4/4 [==============================] - 0s 0us/step - loss: 0.6725 - acc: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 499us/step - loss: 0.6480 - acc: 0.5000
Epoch 4/100
4/4 [==============================] - 0s 499us/step - loss: 0.6246 - acc: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 750us/step - loss: 0.6019 - acc: 0.7500
Epoch 6/100
4/4 [==============================] - 0s 250us/step - loss: 0.5801 - acc: 1.0000
Epoch 7/100
4/4 [==============================] - 0s 250us/step - loss: 0.5594 - acc: 1.0000
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 0.5397 - acc: 1.0000
Epoch 9/100
4/4 [==============================] - 0s 498us/step - loss: 0.5208 - acc: 1.0000
Epoch 10/100
4/4 [==============================] - 0s 250us/step - loss: 0.5028 - acc: 1.0000
Epoch 11/100
4/4 [==============================] - 0s 2

Epoch 71/100
4/4 [==============================] - 0s 996us/step - loss: 0.1332 - acc: 1.0000
Epoch 72/100
4/4 [==============================] - 0s 250us/step - loss: 0.1314 - acc: 1.0000
Epoch 73/100
4/4 [==============================] - 0s 499us/step - loss: 0.1296 - acc: 1.0000
Epoch 74/100
4/4 [==============================] - 0s 249us/step - loss: 0.1279 - acc: 1.0000
Epoch 75/100
4/4 [==============================] - 0s 748us/step - loss: 0.1262 - acc: 1.0000
Epoch 76/100
4/4 [==============================] - 0s 748us/step - loss: 0.1245 - acc: 1.0000
Epoch 77/100
4/4 [==============================] - 0s 499us/step - loss: 0.1229 - acc: 1.0000
Epoch 78/100
4/4 [==============================] - 0s 499us/step - loss: 0.1213 - acc: 1.0000
Epoch 79/100
4/4 [==============================] - 0s 499us/step - loss: 0.1198 - acc: 1.0000
Epoch 80/100
4/4 [==============================] - 0s 494us/step - loss: 0.1182 - acc: 1.0000
Epoch 81/100
4/4 [==============================] 

In [24]:
model.get_weights()

[array([[4.086567 ],
        [4.0464883]], dtype=float32), array([-6.1178794], dtype=float32)]

In [33]:
model.layers[0].get_weights()

[array([[4.086567 ],
        [4.0464883]], dtype=float32), array([-6.1178794], dtype=float32)]

In [11]:
pred = model.predict(X)
pred

array([[0.00219828],
       [0.11190871],
       [0.11595431],
       [0.88238126]], dtype=float32)

In [13]:
predict01 = np.where(pred>0.5, 1, 0)
predict01

array([[0],
       [0],
       [0],
       [1]])

In [15]:
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [16]:
predict03 = (predict02 == y)
predict03

array([ True,  True,  True,  True])

In [17]:
np.sum(predict03)

4

In [19]:
acc = np.sum(predict03)/4
acc

1.0

In [20]:
arr = np.array([[0,1]], dtype = 'float32')
pred = model.predict(arr)
predict01 = np.where(pred>0.5, 1, 0)
predict01

array([[0.11190871]], dtype=float32)

In [22]:
arr = np.array([[1,1]], dtype = 'float32')
pred = model.predict(arr)
predict01 = np.where(pred>0.5, 1, 0)
predict01

array([[1]])