In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import tensorflow as tf

Using TensorFlow backend.


In [2]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
X = data.data
y = data.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
X_train = scaler.transform(X_train)
X_train

array([[-0.3261899 ,  0.01700524, -0.30696324, ..., -0.2331178 ,
         1.14621036,  0.42159961],
       [-0.84795115, -1.19706244, -0.85363265, ..., -1.1247622 ,
        -0.52058549, -0.74462599],
       [-0.3743961 , -1.42929886, -0.43992575, ..., -1.11454794,
        -1.81643755, -0.58120238],
       ...,
       [-0.19007827, -0.120957  , -0.18676183, ...,  0.42960712,
         1.0187495 ,  0.14958889],
       [ 0.4195884 ,  0.02390335,  0.33026888, ..., -0.42688823,
        -0.34573534, -0.84724081],
       [ 1.44042563, -0.16234567,  1.37997296, ...,  1.42699911,
         1.04979766, -0.0518402 ]])

In [7]:
model = Sequential()
model.add(Dense(1,input_dim=30, activation = 'sigmoid'))

In [8]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 31        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.001),metrics=['acc'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [10]:
model.fit(X_train, y_train, epochs=1000)




Epoch 1/1000





455/455 [==============================] - 1s 1ms/step - loss: 1.5993 - acc: 0.1077
Epoch 2/1000
455/455 [==============================] - 0s 50us/step - loss: 1.4374 - acc: 0.1341
Epoch 3/1000
455/455 [==============================] - 0s 64us/step - loss: 1.2904 - acc: 0.1516
Epoch 4/1000
455/455 [==============================] - 0s 42us/step - loss: 1.1551 - acc: 0.1846
Epoch 5/1000
455/455 [==============================] - 0s 61us/step - loss: 1.0346 - acc: 0.2527
Epoch 6/1000
455/455 [==============================] - 0s 48us/step - loss: 0.9253 - acc: 0.3363
Epoch 7/1000
455/455 [==============================] - 0s 44us/step - loss: 0.8352 - acc: 0.4264
Epoch 8/1000
455/455 [==============================] - 0s 55us/step - loss: 0.7541 - acc: 0.4989
Epoch 9/1000
455/455 [==============================] - 0s 55us/step - loss: 0.6884 - acc: 0.5956
Epoch 10/1000
455/455 [==============================] - 0s 37us/step - loss: 0.6304 - acc: 0.6659
Epoch 11/100

455/455 [==============================] - 0s 46us/step - loss: 0.1443 - acc: 0.9670
Epoch 68/1000
455/455 [==============================] - 0s 50us/step - loss: 0.1428 - acc: 0.9670
Epoch 69/1000
455/455 [==============================] - 0s 44us/step - loss: 0.1415 - acc: 0.9670
Epoch 70/1000
455/455 [==============================] - 0s 42us/step - loss: 0.1401 - acc: 0.9670
Epoch 71/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1389 - acc: 0.9670
Epoch 72/1000
455/455 [==============================] - 0s 44us/step - loss: 0.1377 - acc: 0.9670
Epoch 73/1000
455/455 [==============================] - 0s 39us/step - loss: 0.1365 - acc: 0.9670
Epoch 74/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1353 - acc: 0.9670
Epoch 75/1000
455/455 [==============================] - 0s 53us/step - loss: 0.1342 - acc: 0.9670
Epoch 76/1000
455/455 [==============================] - 0s 48us/step - loss: 0.1332 - acc: 0.9670
Epoch 77/1000
455/455 [=

455/455 [==============================] - 0s 44us/step - loss: 0.0905 - acc: 0.9824
Epoch 150/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0902 - acc: 0.9824
Epoch 151/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0899 - acc: 0.9824
Epoch 152/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0896 - acc: 0.9824
Epoch 153/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0893 - acc: 0.9824
Epoch 154/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0889 - acc: 0.9824
Epoch 155/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0886 - acc: 0.9824
Epoch 156/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0883 - acc: 0.9824
Epoch 157/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0881 - acc: 0.9824
Epoch 158/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0878 - acc: 0.9824
Epoch 159/1000


455/455 [==============================] - 0s 39us/step - loss: 0.0734 - acc: 0.9846
Epoch 231/1000
455/455 [==============================] - 0s 37us/step - loss: 0.0732 - acc: 0.9846
Epoch 232/1000
455/455 [==============================] - 0s 37us/step - loss: 0.0731 - acc: 0.9846
Epoch 233/1000
455/455 [==============================] - 0s 37us/step - loss: 0.0730 - acc: 0.9868
Epoch 234/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0728 - acc: 0.9868
Epoch 235/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0727 - acc: 0.9868
Epoch 236/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0725 - acc: 0.9868
Epoch 237/1000
455/455 [==============================] - 0s 35us/step - loss: 0.0724 - acc: 0.9868
Epoch 238/1000
455/455 [==============================] - 0s 37us/step - loss: 0.0723 - acc: 0.9868
Epoch 239/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0722 - acc: 0.9868
Epoch 240/1000


455/455 [==============================] - 0s 53us/step - loss: 0.0650 - acc: 0.9868
Epoch 312/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0650 - acc: 0.9846
Epoch 313/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0649 - acc: 0.9846
Epoch 314/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0648 - acc: 0.9846
Epoch 315/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0647 - acc: 0.9846
Epoch 316/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0647 - acc: 0.9846
Epoch 317/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0646 - acc: 0.9846
Epoch 318/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0646 - acc: 0.9846
Epoch 319/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0645 - acc: 0.9846
Epoch 320/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0644 - acc: 0.9846
Epoch 321/1000


455/455 [==============================] - 0s 44us/step - loss: 0.0603 - acc: 0.9846
Epoch 394/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0603 - acc: 0.9846
Epoch 395/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0602 - acc: 0.9846
Epoch 396/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0602 - acc: 0.9846
Epoch 397/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0602 - acc: 0.9846
Epoch 398/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0601 - acc: 0.9846
Epoch 399/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0601 - acc: 0.9846
Epoch 400/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0600 - acc: 0.9846
Epoch 401/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0600 - acc: 0.9846
Epoch 402/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0600 - acc: 0.9846
Epoch 403/1000


455/455 [==============================] - 0s 46us/step - loss: 0.0575 - acc: 0.9846
Epoch 476/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0575 - acc: 0.9846
Epoch 477/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0574 - acc: 0.9846
Epoch 478/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0574 - acc: 0.9846
Epoch 479/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0573 - acc: 0.9846
Epoch 480/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0572 - acc: 0.9846
Epoch 481/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0573 - acc: 0.9846
Epoch 482/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0572 - acc: 0.9846
Epoch 483/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0572 - acc: 0.9846
Epoch 484/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0571 - acc: 0.9846
Epoch 485/1000


455/455 [==============================] - 0s 53us/step - loss: 0.0553 - acc: 0.9846
Epoch 558/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0553 - acc: 0.9846
Epoch 559/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0553 - acc: 0.9846
Epoch 560/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0553 - acc: 0.9846
Epoch 561/1000
455/455 [==============================] - ETA: 0s - loss: 0.0609 - acc: 0.968 - 0s 48us/step - loss: 0.0552 - acc: 0.9846
Epoch 562/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0552 - acc: 0.9846
Epoch 563/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0552 - acc: 0.9846
Epoch 564/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0552 - acc: 0.9846
Epoch 565/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0552 - acc: 0.9846
Epoch 566/1000
455/455 [==============================] - 0s 48us/step - loss

455/455 [==============================] - 0s 46us/step - loss: 0.0538 - acc: 0.9846
Epoch 639/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0538 - acc: 0.9846
Epoch 640/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0538 - acc: 0.9846
Epoch 641/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0538 - acc: 0.9846
Epoch 642/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0537 - acc: 0.9846
Epoch 643/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0537 - acc: 0.9846
Epoch 644/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0537 - acc: 0.9846
Epoch 645/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0537 - acc: 0.9846
Epoch 646/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0537 - acc: 0.9846
Epoch 647/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0537 - acc: 0.9846
Epoch 648/1000


455/455 [==============================] - 0s 50us/step - loss: 0.0525 - acc: 0.9846
Epoch 721/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0525 - acc: 0.9846
Epoch 722/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0525 - acc: 0.9846
Epoch 723/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0525 - acc: 0.9846
Epoch 724/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0525 - acc: 0.9846
Epoch 725/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0524 - acc: 0.9846
Epoch 726/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0525 - acc: 0.9846
Epoch 727/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0524 - acc: 0.9846
Epoch 728/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0524 - acc: 0.9846
Epoch 729/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0523 - acc: 0.9846
Epoch 730/1000


455/455 [==============================] - 0s 48us/step - loss: 0.0515 - acc: 0.9846
Epoch 803/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0514 - acc: 0.9846
Epoch 804/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0514 - acc: 0.9846
Epoch 805/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0514 - acc: 0.9846
Epoch 806/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0514 - acc: 0.9846
Epoch 807/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0515 - acc: 0.9846
Epoch 808/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0513 - acc: 0.9846
Epoch 809/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0514 - acc: 0.9846
Epoch 810/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0514 - acc: 0.9846
Epoch 811/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0516 - acc: 0.9846
Epoch 812/1000


455/455 [==============================] - 0s 10us/step - loss: 0.0506 - acc: 0.9868
Epoch 885/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0506 - acc: 0.9868
Epoch 886/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0506 - acc: 0.9868
Epoch 887/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0505 - acc: 0.9868
Epoch 888/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0506 - acc: 0.9868
Epoch 889/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0506 - acc: 0.9868
Epoch 890/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0505 - acc: 0.9868
Epoch 891/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0505 - acc: 0.9868
Epoch 892/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0505 - acc: 0.9868
Epoch 893/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0504 - acc: 0.9868
Epoch 894/1000


455/455 [==============================] - 0s 46us/step - loss: 0.0498 - acc: 0.9868
Epoch 966/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0498 - acc: 0.9868
Epoch 967/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0498 - acc: 0.9868
Epoch 968/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0498 - acc: 0.9868
Epoch 969/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0498 - acc: 0.9868
Epoch 970/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0498 - acc: 0.9868
Epoch 971/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0498 - acc: 0.9868
Epoch 972/1000
455/455 [==============================] - ETA: 0s - loss: 0.0023 - acc: 1.000 - 0s 48us/step - loss: 0.0498 - acc: 0.9868
Epoch 973/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0498 - acc: 0.9868
Epoch 974/1000
455/455 [==============================] - 0s 48us/step - loss

In [11]:
X_test = scaler.transform(X_test)

In [12]:
pred = model.predict(X_test)
pred

array([[0.0000000e+00],
       [9.9521631e-01],
       [9.9997944e-01],
       [9.9999857e-01],
       [5.0663948e-07],
       [8.6843967e-05],
       [2.6362240e-03],
       [9.9912405e-01],
       [9.9912918e-01],
       [1.1715293e-04],
       [9.9999601e-01],
       [9.9999678e-01],
       [8.9406967e-08],
       [7.9100293e-01],
       [9.9908954e-01],
       [9.9999875e-01],
       [0.0000000e+00],
       [9.9983150e-01],
       [7.7548623e-04],
       [9.9940914e-01],
       [9.9649322e-01],
       [4.8703587e-01],
       [0.0000000e+00],
       [3.7491322e-05],
       [0.0000000e+00],
       [9.9966800e-01],
       [0.0000000e+00],
       [9.7800791e-01],
       [9.9999964e-01],
       [9.9984652e-01],
       [9.6350908e-05],
       [0.0000000e+00],
       [0.0000000e+00],
       [9.9990106e-01],
       [8.1885654e-01],
       [9.9944496e-01],
       [9.8741400e-01],
       [3.8504601e-05],
       [9.8190808e-01],
       [2.1100044e-05],
       [9.9938631e-01],
       [9.995922

In [14]:
predict01 = np.where(pred>0.5, 1, 0)
print('=========================')
print('predict01')
print(predict01)

predict01
[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]]


In [15]:
predict02 = predict01.flatten()
predict02

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1])

In [16]:
predict03 = (predict02 == y_test)
predict03

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [17]:
np.sum(predict03)

111

In [18]:
len(predict03)

114

In [19]:
acc = np.sum(predict03)/len(predict03)
acc

0.9736842105263158