In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.nn import relu
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
X = np.array(data.data, dtype='float32')
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [4]:
y = np.array(data.target, dtype='float32')

In [5]:
y = y.reshape(-1,1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
X_train = scaler.transform(X_train)
X_train

array([[-5.15501440e-01, -5.48117757e-01, -5.85695863e-01, ...,
        -1.34165704e+00, -1.56976032e+00, -1.43610060e+00],
       [-1.51466262e+00, -4.70780611e-01, -1.42975807e+00, ...,
         9.11002100e-01,  2.10921311e+00,  2.01932693e+00],
       [-9.83274058e-02, -4.98903424e-01, -1.66433975e-01, ...,
        -9.92731333e-01, -8.37760091e-01, -6.93700373e-01],
       ...,
       [ 2.51276046e-01, -6.09050095e-01,  2.72001296e-01, ...,
        -2.13177294e-01, -1.13340580e+00,  1.18188776e-01],
       [ 8.67565945e-02,  4.97105479e-01,  8.11177790e-02, ...,
         1.04725920e-01,  1.99371994e-01, -8.93257320e-01],
       [-1.07141145e-01,  1.20720148e+00, -6.89300708e-04, ...,
         5.59312105e-01,  1.19697952e+00,  2.06684041e+00]], dtype=float32)

In [9]:
def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [10]:
# w와 b를 초기화 시켜주는 객체
initializer = tf.contrib.layers.xavier_initializer()

w = tf.Variable(initializer([30,1]))
w

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[-0.38172162],
       [-0.15476117],
       [ 0.2136485 ],
       [ 0.3583119 ],
       [-0.41934258],
       [-0.1383706 ],
       [-0.3828531 ],
       [-0.20922677],
       [ 0.17140418],
       [ 0.35655797],
       [-0.12271932],
       [ 0.05573413],
       [-0.06128672],
       [-0.05311397],
       [-0.2659968 ],
       [-0.05170867],
       [-0.08342871],
       [ 0.26299256],
       [ 0.24732077],
       [ 0.16217315],
       [ 0.26804656],
       [-0.22039841],
       [ 0.02596337],
       [ 0.36334258],
       [-0.18620777],
       [ 0.187778  ],
       [-0.13305426],
       [-0.31762564],
       [-0.27454305],
       [-0.0614346 ]], dtype=float32)>

In [11]:
b = tf.Variable(initializer([1]))
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-1.0255277], dtype=float32)>

In [13]:
tf.matmul(X_train, w)+b

<tf.Tensor: id=35, shape=(455, 1), dtype=float32, numpy=
array([[ 1.2415924e+00],
       [-2.7599778e+00],
       [ 1.1423826e-02],
       [-1.4209193e+00],
       [-1.5900010e-01],
       [-9.7987276e-01],
       [-3.2668762e+00],
       [-7.6743603e-01],
       [-1.2477200e+00],
       [-4.7763950e-01],
       [-9.8683476e-01],
       [-4.5484364e-02],
       [ 1.6021228e-01],
       [-2.5634522e+00],
       [-1.8108679e+00],
       [ 2.9799438e-01],
       [-1.1849520e+00],
       [-4.3166292e-01],
       [-1.4764595e+00],
       [-3.0343091e+00],
       [ 1.2586176e-01],
       [-2.0696054e+00],
       [ 4.2706239e-01],
       [-4.8002547e-01],
       [-1.8448085e+00],
       [-9.4203353e-02],
       [ 1.4241529e-01],
       [-3.7874610e+00],
       [ 4.7753263e-01],
       [-1.3882262e-01],
       [-7.5214875e-01],
       [-2.1933224e+00],
       [-1.0767776e-01],
       [-3.6740184e-02],
       [ 3.5051489e-01],
       [-1.8282206e+00],
       [-6.3478076e-01],
       [-4.2480364

In [14]:
hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b)
hypothesis

<tf.Tensor: id=41, shape=(455, 1), dtype=float32, numpy=
array([[0.77584106],
       [0.05952561],
       [0.5028559 ],
       [0.19451752],
       [0.46033353],
       [0.27291703],
       [0.03672519],
       [0.317034  ],
       [0.22309506],
       [0.3828097 ],
       [0.27153772],
       [0.48863086],
       [0.5399676 ],
       [0.07152787],
       [0.14053324],
       [0.57395214],
       [0.23416299],
       [0.39372933],
       [0.18596277],
       [0.04589972],
       [0.531424  ],
       [0.11208636],
       [0.605172  ],
       [0.3822461 ],
       [0.13648361],
       [0.47646657],
       [0.53554374],
       [0.02215123],
       [0.6171651 ],
       [0.46534997],
       [0.3203533 ],
       [0.10035175],
       [0.47310653],
       [0.490816  ],
       [0.5867424 ],
       [0.13845035],
       [0.34642732],
       [0.01409087],
       [0.17455357],
       [0.08374846],
       [0.35610494],
       [0.28694314],
       [0.35915375],
       [0.29094523],
       [0.2690447 ]

In [15]:
optimizer = tf.train.AdamOptimizer(0.001)

In [16]:
for step in range(100):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b)
        cost = -tf.reduce_mean(y_train * tf.log(hypothesis) + (1 - y_train) * tf.log(1 - hypothesis))
        grads = tape.gradient(cost, [w,b])
    optimizer.apply_gradients(grads_and_vars = zip(grads, [w,b]))
    
    if step % 10 == 0:
        print("=" * 50)
        print(f"step: {step}, cost : {cost}, w : {w.numpy()}, b : {b.numpy()}")
        print('=' * 50)

step: 0, cost : 0.7395007014274597, w : [[-0.3827216 ]
 [-0.15576117]
 [ 0.2126485 ]
 [ 0.3573119 ]
 [-0.42034256]
 [-0.1393706 ]
 [-0.38385308]
 [-0.21022677]
 [ 0.17040418]
 [ 0.35755795]
 [-0.12371932]
 [ 0.0567341 ]
 [-0.06228672]
 [-0.05411397]
 [-0.26499683]
 [-0.05270867]
 [-0.08442871]
 [ 0.26199257]
 [ 0.2463208 ]
 [ 0.16117316]
 [ 0.26704657]
 [-0.22139841]
 [ 0.02496337]
 [ 0.3623426 ]
 [-0.18720777]
 [ 0.186778  ]
 [-0.13405426]
 [-0.31862563]
 [-0.27554303]
 [-0.06243459]], b : [-1.0245277]
step: 10, cost : 0.6885939240455627, w : [[-0.39268994]
 [-0.16572484]
 [ 0.20268096]
 [ 0.34734425]
 [-0.43021756]
 [-0.14931722]
 [-0.3938089 ]
 [-0.22018723]
 [ 0.1604642 ]
 [ 0.36758807]
 [-0.13368279]
 [ 0.06675673]
 [-0.07224879]
 [-0.06407793]
 [-0.2550019 ]
 [-0.06262816]
 [-0.09432577]
 [ 0.25205284]
 [ 0.2364696 ]
 [ 0.15136774]
 [ 0.2570789 ]
 [-0.23136026]
 [ 0.01499662]
 [ 0.35237572]
 [-0.19710927]
 [ 0.17682777]
 [-0.14400731]
 [-0.32858428]
 [-0.2854972 ]
 [-0.07236064]]

In [17]:
X_test = scaler.transform(X_test)
X_test

array([[-0.9532406 , -0.17549321, -0.93550664, ..., -0.5653281 ,
        -1.0164124 , -0.3670441 ],
       [ 1.7348878 ,  1.059558  ,  1.8046069 , ...,  1.1766894 ,
         0.6325647 ,  0.6645953 ],
       [ 0.2277733 , -0.05597209,  0.19956768, ...,  0.5101677 ,
         0.10767467,  0.07245677],
       ...,
       [ 3.0686693 ,  0.5299155 ,  3.1169305 , ...,  2.0244315 ,
         0.41596833,  0.7845668 ],
       [-0.38036054, -0.8527793 , -0.35220444, ..., -0.21471308,
        -1.4148228 , -0.7263661 ],
       [ 1.1061893 ,  0.15729095,  0.93114513, ...,  0.04329534,
         3.1431835 , -1.3297887 ]], dtype=float32)

In [18]:
predict = tf. sigmoid(tf.matmul(X_test, w) + b)
predict

<tf.Tensor: id=6438, shape=(114, 1), dtype=float32, numpy=
array([[5.3873682e-01],
       [1.7782986e-02],
       [3.0581254e-01],
       [4.8395798e-01],
       [6.8538678e-01],
       [3.3559421e-01],
       [6.1731207e-01],
       [1.4187217e-02],
       [8.8501960e-02],
       [7.8102803e-01],
       [2.2671115e-01],
       [4.3403354e-01],
       [1.4591724e-02],
       [2.5942835e-01],
       [9.2612743e-01],
       [3.8991883e-01],
       [2.6333413e-01],
       [2.1548569e-03],
       [2.1816850e-02],
       [9.3414760e-01],
       [4.9406797e-01],
       [2.5099784e-02],
       [9.1599751e-01],
       [6.6170353e-01],
       [5.8035880e-02],
       [4.2710721e-02],
       [4.4216233e-01],
       [1.1733800e-02],
       [4.4355872e-01],
       [4.3646738e-01],
       [4.8660904e-01],
       [8.3035958e-01],
       [5.3954720e-01],
       [5.6109393e-01],
       [5.2432907e-01],
       [3.7942496e-01],
       [6.2728918e-01],
       [2.4150249e-01],
       [5.2146220e-01],
     

In [19]:
predict01  =tf.cast(predict >0.5, dtype = tf.float32)
ac01 = tf.equal(predict01, y_test)
ac01

<tf.Tensor: id=6443, shape=(114, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],


In [20]:
ac02 = tf.cast(ac01, dtype='float32')
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=6446, shape=(), dtype=float32, numpy=0.78070176>