In [1]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
X = np.array(
    [
        [0,0],
        [0,1],
        [1,0],
        [1,1]
    ], dtype='float32'
)

In [3]:
y = np.array(
    [
        [0],
        [1],
        [1],
        [0]
    ], dtype='float32'
)

In [4]:
w0 = np.array([
    [1,2],
    [3,4]
], dtype = 'float32')
w0

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [5]:
w0 = tf.Variable(w0)

In [6]:
b0 = tf.Variable([[0,0]], dtype='float32')
b0

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [7]:
tf.matmul(X, w0) + b0

<tf.Tensor: id=21, shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [3., 4.],
       [1., 2.],
       [4., 6.]], dtype=float32)>

In [8]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
hypothesis0

<tf.Tensor: id=27, shape=(4, 2), dtype=float32, numpy=
array([[0.5       , 0.5       ],
       [0.95257413, 0.98201376],
       [0.7310586 , 0.8807971 ],
       [0.98201376, 0.99752736]], dtype=float32)>

In [9]:
w1 = tf.Variable([[5],[6]], dtype = 'float32')
w1

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[5.],
       [6.]], dtype=float32)>

In [10]:
b1 = tf.Variable([[0]], dtype = 'float32')
b1

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.]], dtype=float32)>

In [11]:
tf.matmul(hypothesis0, w1) + b1

<tf.Tensor: id=49, shape=(4, 1), dtype=float32, numpy=
array([[ 5.5     ],
       [10.654953],
       [ 8.940075],
       [10.895233]], dtype=float32)>

In [12]:
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1))
hypothesis1

<tf.Tensor: id=52, shape=(4, 1), dtype=float32, numpy=
array([[0.9959299],
       [0.9999764],
       [0.999869 ],
       [0.9999814]], dtype=float32)>

In [13]:
optimizer = tf.train.AdamOptimizer(0.1)

In [14]:
for step in range(5000):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
        hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
        cost = -tf.reduce_mean(y * tf.log(hypothesis1) + (1 - y) * tf.log(1 - hypothesis1))
    grads = tape.gradient(cost, [w0,w1,b0,b1])
    optimizer.apply_gradients(grads_and_vars = zip(grads, [w0,w1,b0,b1]))

    if step % 100 == 0:
        print('cost:{},w0:{},w1:{}'.format(cost,w0,w1))

cost:4.0991926193237305,w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.9000014, 1.9000086],
       [2.9000015, 3.9000084]], dtype=float32)>,w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[4.9],
       [5.9]], dtype=float32)>
cost:0.557486355304718,w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.0565376, -4.4126096],
       [ 1.2810546,  3.060032 ]], dtype=float32)>,w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.685531 ],
       [3.8502126]], dtype=float32)>
cost:0.5103297233581543,w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.5863264, -6.2746296],
       [ 1.5904136,  4.880547 ]], dtype=float32)>,w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.3543894],
       [4.411695 ]], dtype=float32)>
cost:0.49529534578323364,w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.8877606, -7.3770666],
       [ 1.6697836,

cost:0.00204339437186718,w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -8.085321, -12.427614],
       [  8.573951,  12.442619]], dtype=float32)>,w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-12.558692],
       [ 13.109066]], dtype=float32)>
cost:0.001675998792052269,w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -8.184335, -12.440248],
       [  8.684058,  12.500908]], dtype=float32)>,w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-12.950263],
       [ 13.491261]], dtype=float32)>
cost:0.0014093072386458516,w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -8.269622, -12.452357],
       [  8.777928,  12.548829]], dtype=float32)>,w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-13.292454],
       [ 13.826859]], dtype=float32)>
cost:0.0012071061646565795,w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -8.344806 , 

In [15]:
w0

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -9.124643, -12.649009],
       [  9.688229,  12.943771]], dtype=float32)>

In [16]:
b0

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[ 4.2849054, -7.1995916]], dtype=float32)>

In [17]:
w1

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-17.039648],
       [ 17.550507]], dtype=float32)>

In [18]:
b1

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[8.180047]], dtype=float32)>

In [19]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)

predict = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
predict

<tf.Tensor: id=415358, shape=(4, 1), dtype=float32, numpy=
array([[1.8133699e-04],
       [9.9982232e-01],
       [9.9967980e-01],
       [1.6499007e-04]], dtype=float32)>

In [20]:
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)
print(predict01)

tf.Tensor(
[[0.]
 [1.]
 [1.]
 [0.]], shape=(4, 1), dtype=float32)


In [21]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype = tf.float32))
accuracy.numpy()

1.0

In [22]:
### 예측

In [23]:
arr = np.array([[0,1]], dtype='float32')
hypothesis0 = tf.sigmoid(tf.matmul(arr, w0) + b0)
predict = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
predict = tf.cast(predict >0.5, dtype=tf.float32)
predict.numpy()

array([[1.]], dtype=float32)

In [24]:
arr = np.array([[1,1]], dtype='float32')
hypothesis0 = tf.sigmoid(tf.matmul(arr, w0) + b0)
predict = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
predict = tf.cast(predict >0.5, dtype=tf.float32)
predict.numpy()

array([[0.]], dtype=float32)