In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import keras
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [2]:
print(keras.__version__)

2.2.5


In [3]:
from google.colab import drive

drive.mount('gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at gdrive


In [0]:
#학습 데이터의 경로
TRAIN_DIR = './gdrive/My Drive/ai/workspace/data/dental_image/train/'
#테스트 데이터의 경로
TEST_DIR = './gdrive/My Drive/ai/workspace/data/dental_image/test/'

In [0]:
#이미지의 가로 세로
IM_WIDTH = 220
IM_HEIGHT = 220

In [0]:
#학습에 사용될 이미지를 읽을 객체

# 실행할때마다 변형된 이미지를 리턴해서 
#이미지가 많은것 같은 효과를 줌
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
      rotation_range=180, # 회전 쵀대 180도
      width_shift_range=0.2, # 좌우 이동 최대 이미지 가로사이즈 20%
      height_shift_range=0.2, # 상하 이동 최대 이미지  세로사이즈 20%
      horizontal_flip=True, # 좌우 반전 실행
      vertical_flip=True # 상하 반전 실행 
      )

In [7]:
#train_datagen.flow_from_directory() : 디렉토리에서 이미지를 읽을 객체를 생성
#train_datagen.flow_from_directory(
#        이미지 경로,       : TRAIN_DIR (/dental_image/train/)
#        target_size=(이미지가로, 이미지세로), IM_WIDTH (220) x IM_HEIGHT(220)
#        batch_size=한번에 리턴할 이미지의 개수, 50개
#        class_mode=분류방법, categorical (다중분류) binary(0 1 로 이중 분류)
#        shuffle=이미지를 섞을 여부
#)
        
train_generator = train_datagen.flow_from_directory(
         TRAIN_DIR,
        target_size=(IM_WIDTH, IM_HEIGHT),
        batch_size=8,
        class_mode='categorical',
        shuffle=True)

Found 150 images belonging to 3 classes.


In [0]:
# 검증에 사용될 이미지를 읽을 객체
#테스트에서는 이미지를 변형 할 필요가 없으므로
#ImageDataGenerator에 값을 주지 않음
#이미지가 변형되지 않고 같은 이미지 리턴
test_datagen = ImageDataGenerator(rescale=1.0/255)

In [9]:
#test_datagen.flow_from_directory() : 디렉토리에서 이미지를 읽을 객체를 생성
#test_datagen.flow_from_directory(
#        이미지 경로,       : TEST_DIR (/dental_image/test/)
#        target_size=(이미지가로, 이미지세로), IM_WIDTH (220) x IM_HEIGHT(220)
#        batch_size=한번에 리턴할 이미지의 개수, 10개
#        class_mode=분류방법, categorical (다중분류) binary(0 1 로 이중 분류)
#        shuffle=이미지를 섞을 여부 False 섞지 않음
#)
        
test_generator = test_datagen.flow_from_directory(
        TEST_DIR,
        target_size=(IM_WIDTH, IM_HEIGHT),
        batch_size=60,
        class_mode='categorical',
        shuffle=False)

Found 60 images belonging to 3 classes.


In [10]:
#학습데이터의 전체 이미지 개수를 리턴
train_generator.n

150

In [11]:
#한번에 리턴할 이미지의 개수 
train_generator.batch_size

8

In [12]:
#테스트 데이터의 전체 이미지 개수를 리턴
test_generator.n

60

In [0]:
#train_generator.next()
#train_generator.batch_size 에 설정된 이미지 50개를 리턴해서 img에 대입
#이지지의 label을 label에 대입
img, label = train_generator.next()

In [14]:
img

array([[[[0.31068456, 0.07539043, 0.07146886],
         [0.31627816, 0.08269518, 0.07740469],
         [0.30562592, 0.08535824, 0.06941549],
         ...,
         [0.39950034, 0.27779046, 0.22516975],
         [0.4076477 , 0.26676443, 0.2194124 ],
         [0.40189034, 0.2696431 , 0.21365504]],

        [[0.30843827, 0.07697798, 0.06538872],
         [0.31003773, 0.0747436 , 0.07082203],
         [0.3171406 , 0.08247957, 0.07805152],
         ...,
         [0.40748954, 0.26713818, 0.21984361],
         [0.40232155, 0.26942748, 0.21408625],
         [0.40000004, 0.27058825, 0.2083289 ]],

        [[0.31137496, 0.09019608, 0.06062961],
         [0.30886948, 0.07805602, 0.06517311],
         [0.3093909 , 0.07409678, 0.07017521],
         ...,
         [0.40275276, 0.2692119 , 0.21451746],
         [0.40000004, 0.27058825, 0.20876011],
         [0.40000004, 0.27058825, 0.20392159]],

        ...,

        [[0.4525419 , 0.26666668, 0.16877647],
         [0.4281902 , 0.2662971 , 0.14191565]

In [15]:
img.shape

(8, 220, 220, 3)

In [16]:
label

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

In [17]:
label.shape

(8, 3)

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D,MaxPooling2D
from keras.optimizers import Adam

In [19]:
from keras.applications.resnet50 import ResNet50

#Resnet50 구조를 갖는 Model생성
conv_layers = ResNet50(weights='imagenet', include_top=False, input_shape=(IM_WIDTH, IM_HEIGHT, 3))

/usr/local/lib/python3.6/dist-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


94658560/94653016 [==============================] - 2s 0us/step


In [20]:
conv_layers.summary()

Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 220, 220, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 226, 226, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 110, 110, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 110, 110, 64) 256         conv1[0][0]                      
___________________________________________________________________________________________

In [0]:
#입력값을 읽어서 예측을 할 Sequential 객체 생성
model = Sequential()

In [0]:
#Resnet50대입
model.add(conv_layers)

In [0]:
#선형 회귀를 하기 위해서 합성곱 연산을 수행한 결과를 1차원 배열로 변환
model.add(Flatten())

In [24]:
#Dense : 선형 회귀를 수행할 객체
#Dense(출력데이터의 칸의수) : 출력 데이터는 y_h1이고 칸의 수는 512 이므로
#Dense(512)  
# activation="relu" :선형 회귀 후 relu 활성 함수 사용
#model.add(Dense(512, activation='relu')) :Dense 모델을 예측 할 수 있도록 model에 추가
model.add(Dense(512, activation='relu'))

In [25]:
model.add(Dropout(0.5))

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [0]:
#Dense : 선형 회귀를 수행할 객체
#Dense(출력데이터의 칸의수) : 출력 데이터 칸의 수는 3이므로
#Dense(3)

#Dense(3) : 선형 회귀를 할 객체를 생성  출력 칸수는 3
    
# activation="softmax" :선형 회귀 후 softmax 함수를 활성 함수를 이용해서 0~1사이 값을 리턴  
    
    
#model.add(Dense(3, activation="softmax")):Dense 모델을 예측 할 수 있도록 model에 추가
model.add(Dense(3, activation='softmax'))

In [27]:
#생성된 모델 정보 출력
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
resnet50 (Model)             (None, 7, 7, 2048)        23587712  
_________________________________________________________________
flatten_1 (Flatten)          (None, 100352)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               51380736  
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 1539      
Total params: 74,969,987
Trainable params: 74,916,867
Non-trainable params: 53,120
_________________________________________________________________


In [28]:
#GradientDecnet를 이용해서 w0,b0와 w1,b1를 찾는 방법을 설정함
#loss='categorical_crossentropy' : -(y * tf.log(hypothesis1)) 합 이 최소가 되는 w1,w2,w3,w4 를 찾음
#optimizer=Adam(lr=1e-4) : learning rate를 0.00001 로 설정
model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=1e-5),metrics=['acc'])

In [29]:
#model.fit(train_generator ,epochs=15) :train_generator 를 이용해서 이미지를 리턴 받음 (epach를 진행할때 마다 증강된 이미지 리턴)
#                                       epochs=15 - 50개씩 3번 150개 이미지를 15번 반복해서 학습
model.fit(train_generator , epochs=50)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/50
19/19 [==============================] - 43s 2s/step - loss: 2.1600 - acc: 0.4033
Epoch 2/50
19/19 [==============================] - 3s 179ms/step - loss: 1.5738 - acc: 0.5284
Epoch 3/50
19/19 [==============================] - 4s 196ms/step - loss: 1.4700 - acc: 0.5527
Epoch 4/50
19/19 [==============================] - 4s 190ms/step - loss: 1.0682 - acc: 0.6469
Epoch 5/50
19/19 [==============================] - 4s 199ms/step - loss: 1.2707 - acc: 0.5943
Epoch 6/50
19/19 [==============================] - 4s 193ms/step - loss: 1.0881 - acc: 0.6712
Epoch 7/50
19/19 [==============================] - 4s 187ms/step - loss: 1.3834 - acc: 0.6164
Epoch 8/50
19/19 [==============================] - 4s 190ms/step - loss: 0.9209 - acc: 0.6798
Epoch 9/50
19/19 [==============================] - 4s 190ms/step - loss: 0.7631 - acc: 0.7301
Epoch 10/50
19/19 [==============================] 

In [0]:
#test_generator.next()
#test_generator.batch_size 에 설정된 이미지 60개를 리턴해서 X_test에 대입
#이미지의 label을 y_test에 대입
X_test,y_test = test_generator.next()

In [31]:
X_test

array([[[[0.90196085, 0.8352942 , 0.7176471 ],
         [0.9176471 , 0.8352942 , 0.72156864],
         [0.9294118 , 0.8352942 , 0.7254902 ],
         ...,
         [0.7686275 , 0.5647059 , 0.5803922 ],
         [0.77647066, 0.57254905, 0.5882353 ],
         [0.7725491 , 0.5686275 , 0.58431375]],

        [[0.91372555, 0.8313726 , 0.7254902 ],
         [0.92549026, 0.8313726 , 0.7294118 ],
         [0.9294118 , 0.8352942 , 0.73333335],
         ...,
         [0.8745099 , 0.67058825, 0.6862745 ],
         [0.86666673, 0.6627451 , 0.6784314 ],
         [0.8470589 , 0.6509804 , 0.6627451 ]],

        [[0.909804  , 0.8235295 , 0.7294118 ],
         [0.9215687 , 0.82745105, 0.7254902 ],
         [0.9215687 , 0.82745105, 0.7254902 ],
         ...,
         [0.854902  , 0.65882355, 0.67058825],
         [0.85098046, 0.654902  , 0.6666667 ],
         [0.8470589 , 0.6509804 , 0.6627451 ]],

        ...,

        [[0.49803925, 0.24705884, 0.2392157 ],
         [0.48627454, 0.23529413, 0.227451  ]

In [32]:
y_test

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [33]:
# model.predict(X_test) : 
#X_test가 어떤 이미지인지 분류
predict =model.predict(X_test)
predict

array([[9.99101400e-01, 8.84885842e-04, 1.37168599e-05],
       [8.86755884e-01, 7.23559931e-02, 4.08880971e-02],
       [2.16067731e-01, 1.68363564e-02, 7.67095923e-01],
       [2.52713412e-01, 7.40138054e-01, 7.14848423e-03],
       [9.97941196e-01, 8.88374751e-04, 1.17037550e-03],
       [3.54792207e-01, 8.87638479e-02, 5.56443930e-01],
       [5.84292352e-01, 1.50303086e-02, 4.00677383e-01],
       [9.99968767e-01, 1.68287006e-05, 1.44006808e-05],
       [9.90022719e-01, 7.99573865e-03, 1.98151590e-03],
       [5.94176292e-01, 1.88448783e-02, 3.86978805e-01],
       [9.65278149e-01, 3.46738063e-02, 4.80145427e-05],
       [9.96810138e-01, 6.81631718e-05, 3.12166032e-03],
       [5.62616508e-04, 2.96124071e-01, 7.03313351e-01],
       [9.54875588e-01, 4.01532911e-02, 4.97102737e-03],
       [3.92674934e-03, 2.05758944e-01, 7.90314317e-01],
       [9.99976397e-01, 2.30113856e-05, 5.63341246e-07],
       [9.99949813e-01, 3.33664798e-06, 4.68170692e-05],
       [9.99987721e-01, 1.17255

In [34]:
#np.argmax(predict,1) : predict 최대값의 인덱스를 리턴
#                  1: 각 줄에서 최대 값의 인덱스를 리턴
predict01 = np.argmax(predict,1)
predict01

array([0, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [35]:
#np.argmax(y_test,1) : y_test 최대값의 인덱스를 리턴
#                  1: 각 줄에서 최대 값의 인덱스를 리턴
target = np.argmax(y_test, 1)
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [36]:
#predict01 == target 가 같으면 true 다르면 false 리턴
predict02 = (predict01 == target)
predict02

array([ True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [37]:
#True는 1로 False는 0으로 변환 해서 합을 계산
np.sum(predict02)

51

In [38]:
#정확도를 계산
#len(predict02) : redict02의 줄의 수를 리턴
acc=np.sum(predict02)/len(predict02)
acc

0.85

In [39]:
#레이블의 이름을 리턴
train_generator.class_indices.keys()

dict_keys(['cured', 'decayed', 'healthy'])

In [40]:
##레이블의 이름을 리스트로 변환해서 custom_labels에 대입
custom_labels = list(train_generator.class_indices.keys())
custom_labels

['cured', 'decayed', 'healthy']

In [41]:
custom_labels[0]

'cured'

In [42]:
custom_labels[1]

'decayed'

In [43]:
custom_labels[2]

'healthy'

In [44]:
#이미지를 출력할 객체
fig = plt.figure(figsize=(20,60))
for i in range(60):
    #4줄 5칸으로 나누고 i+1번째 이미지를 그림
    subplot = fig.add_subplot(12, 5, i + 1)
    
    #subplot.set_xticks([]) : 그래프의 x축을 설정 
    #데이터가 없으므로 x축에 아무 데이터도 출력 안됨
    subplot.set_xticks([])
    
    #subplot.set_yticks([]) : 그래프의 y축을 설정 
    #데이터가 없으므로 y축에 아무 데이터도 출력 안됨
    subplot.set_yticks([])
    #예측값(숫자)을 predict_num에 대입
    predict_num=predict01[i]
    #예측값에 해당하는 문자를 리턴
    predict_str=custom_labels[predict_num]
    #실제 값(숫자) 리턴
    target_num=target[i]
    #실제 값에 해당하는 문자 리턴
    target_str=custom_labels[target_num]
    #이미지의 제목으로 예측한 이미지의 이름, 실제 이름 출력
    subplot.set_title('predict: %s, target:%s' % (predict_str,target_str))
    #X_test[i]를 255로 나눠서 0~1 사이 범위로 변환
    #X_test[i]=X_test[i]/255.0
    #이미지 출력
    subplot.imshow(X_test[i].reshape((220, 220,3)),
                   cmap=plt.cm.gray_r)
#그래프를 화면에 그림
plt.show()

Output hidden; open in https://colab.research.google.com to view.