In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

Using TensorFlow backend.


In [2]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
X = data.data

In [4]:
y = data.target

In [5]:
y = y.reshape(-1, 1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [7]:
X_train.shape

(120, 4)

In [8]:
y_train.shape

(120, 1)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
X_train = scaler.transform(X_train)
X_train

array([[ 0.69210212, -0.57139548,  0.41487917,  0.34147769],
       [-0.73573033,  1.43872542, -1.34292324, -1.38808462],
       [ 1.64399042, -0.34804871,  1.37883533,  0.74060745],
       [-0.6167443 ,  1.88541895, -1.22951663, -1.12199811],
       [-0.85471637,  0.99203188, -1.34292324, -1.38808462],
       [ 1.40601835, -0.12470194,  1.15202212,  1.13973721],
       [-0.6167443 ,  1.43872542, -1.34292324, -1.38808462],
       [-0.37877222, -0.57139548,  0.58498908,  1.00669395],
       [-1.21167449, -1.24143577,  0.35817587,  0.60756419],
       [ 0.45413004, -0.34804871,  0.98191221,  0.74060745],
       [-0.49775826, -1.46478254, -0.09545056, -0.32373858],
       [-0.02181411, -0.12470194,  0.69839569,  0.74060745],
       [ 0.57311608, -0.79474224,  0.8118023 ,  0.8736507 ],
       [-1.09268845,  0.76868512, -1.28621994, -1.12199811],
       [-1.44964656,  0.32199159, -1.28621994, -1.38808462],
       [-1.21167449, -0.12470194, -1.39962655, -1.38808462],
       [-0.97370241,  1.

In [11]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(categories = 'auto')
enc.fit(y)

OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [12]:
y_train_onehot = enc.transform(y_train).toarray()
y_train_onehot

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [13]:
y_train_onehot = np.array(y_train_onehot, dtype='float32')

In [14]:
y_train_onehot

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [15]:
y_test_onehot = enc.transform(y_test).toarray()
y_test_onehot = np.array(y_test_onehot, dtype='float32')

In [16]:
model = Sequential()

model.add(Dense(16, input_dim = 4, activation = 'sigmoid'))
model.add(Dense(3,activation = 'softmax'))

In [17]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=0.1),metrics=['acc'])

In [19]:
model.fit(X_train, y_train_onehot, epochs = 1000)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/1000





120/120 [==============================] - 0s 2ms/step - loss: 0.9424 - acc: 0.4500
Epoch 2/1000
120/120 [==============================] - 0s 58us/step - loss: 0.4635 - acc: 0.8250
Epoch 3/1000
120/120 [==============================] - 0s 66us/step - loss: 0.3582 - acc: 0.8333
Epoch 4/1000
120/120 [==============================] - 0s 58us/step - loss: 0.2889 - acc: 0.8917
Epoch 5/1000
120/120 [==============================] - 0s 50us/step - loss: 0.2071 - acc: 0.9333
Epoch 6/1000
120/120 [==============================] - 0s 66us/step - loss: 0.1989 - acc: 0.9083
Epoch 7/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1417 - acc: 0.9583
Epoch 8/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1284 - acc: 0.9500
Epoch 9/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0973 - acc: 0.9583
Epoch 10/1000
120

In [20]:
X_test = scaler.transform(X_test)

In [21]:
pred = model.predict(X_test)

In [22]:
np.where(pred>0.5, 1, 0)

array([[0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [23]:
predict = np.argmax(pred,1)

In [24]:
target = np.argmax(y_test_onehot, 1)

In [25]:
predict02 = (predict == target)

In [26]:
np.sum(predict02)/len(predict02)

0.9666666666666667