In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.nn import relu
import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [3]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = data.data
y = data.target

In [5]:
X = np.array(X,dtype="float32")
y = np.array(y,dtype="float32")
y.shape

(150,)

In [6]:
X.shape

(150, 4)

In [7]:
y= y.reshape(-1,1)

In [8]:
y.shape

(150, 1)

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
enc = OneHotEncoder()

In [12]:
enc.fit(y)

C:\Users\JMLAP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [13]:
y_train_onehot = enc.transform(y_train).toarray()
y_train_onehot

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [14]:
y_train_onehot = np.array(y_train_onehot,dtype='float32')
y_train_onehot

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
y_test_onehot = enc.transform(y_test).toarray()
y_test_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [16]:
y_test_onehot = np.array(y_test_onehot, dtype = 'float32')

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train

array([[ 0.2369402 , -0.84837323,  0.81958795,  0.5817336 ],
       [ 0.3594953 , -0.16204883,  0.535666  ,  0.31780902],
       [ 0.3594953 , -0.61959857,  0.5924503 ,  0.05388459],
       [ 2.3203785 , -0.61959857,  1.728138  ,  1.1095827 ],
       [-0.13072567,  3.0407991 , -1.2246498 , -1.0018135 ],
       [-0.00816999, -0.84837323,  0.2517441 , -0.21004   ],
       [ 0.3594953 , -0.61959857,  0.19495976,  0.18584672],
       [ 1.2173822 ,  0.2955009 ,  1.2738631 ,  1.5054693 ],
       [ 0.2369402 , -1.9922473 ,  0.7628036 ,  0.4497713 ],
       [-0.13072567,  1.6681497 , -1.1110809 , -1.1337758 ],
       [ 0.72716117,  0.2955009 ,  0.93315685,  1.5054693 ],
       [ 1.5850474 , -0.16204883,  1.2738631 ,  1.2415448 ],
       [-0.98861194,  0.52427554, -1.2814342 , -1.2657381 ],
       [-0.98861194,  0.98182535, -1.1678654 , -0.737889  ],
       [ 1.2173822 , -0.16204883,  1.0467255 ,  1.2415448 ],
       [-1.478833  ,  1.2105999 , -1.5085716 , -1.2657381 ],
       [ 0.3594953 , -0.

In [18]:
initializer = tf.contrib.layers.xavier_initializer()

w0 = tf.Variable(initializer([4,16]))
w0

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



<tf.Variable 'Variable:0' shape=(4, 16) dtype=float32, numpy=
array([[-0.00385833,  0.15095675,  0.40850496,  0.4750452 ,  0.3865283 ,
        -0.1007871 ,  0.17683709, -0.3279364 ,  0.01425987, -0.22517836,
        -0.11308438,  0.12068778, -0.09995526, -0.15164182, -0.25497565,
        -0.16788584],
       [ 0.36302245, -0.45384145,  0.20532691,  0.09382874, -0.49240112,
         0.42373312, -0.29240727,  0.0261693 ,  0.45937705, -0.49181858,
        -0.4846428 ,  0.08859223,  0.1682679 , -0.25838682, -0.01552105,
         0.53894794],
       [ 0.11561686,  0.40689993, -0.11456653,  0.39715052,  0.08900344,
         0.14630187,  0.53513   ,  0.23466146, -0.16007489,  0.49494112,
         0.17963904, -0.26805446,  0.05569613, -0.40435958,  0.5074475 ,
         0.11171818],
       [-0.31830025, -0.47616392, -0.18634683, -0.54741335,  0.2104792 ,
        -0.45961535,  0.21917474,  0.4152128 ,  0.397772  , -0.07485783,
        -0.5374024 ,  0.43625355, -0.47406447,  0.04832864,  0.251838

In [19]:
b0 = tf.Variable(initializer([16]))

In [20]:
w1 = tf.Variable(initializer([16,3]))

In [21]:
b1 = tf.Variable(initializer([3]))

In [22]:
tf.matmul(X_train, w0) + b0

<tf.Tensor: id=59, shape=(120, 16), dtype=float32, numpy=
array([[-0.31642205,  0.31310642, -0.57004607, ..., -0.39528975,
         0.20546237, -0.34212503],
       [-0.01656264,  0.03026804, -0.29735133, ..., -0.48915997,
        -0.0469805 , -0.1333541 ],
       [-0.09209104,  0.38669991, -0.34862268, ..., -0.40665156,
        -0.0775301 , -0.48243335],
       ...,
       [ 0.04307507, -0.0104851 , -0.42240518, ..., -0.33573183,
        -0.1037128 , -0.18525594],
       [ 0.82337356, -0.73721755, -0.08842382, ...,  0.03103322,
        -1.0474163 , -0.0570474 ],
       [ 0.15184769,  0.01222336,  0.24067014, ..., -0.7976065 ,
        -0.30650443, -0.06559233]], dtype=float32)>

In [23]:
optimizer = tf.train.AdamOptimizer(0.1)

In [24]:
for step in range(1001):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
        hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
        cost = -tf.reduce_sum(y_train_onehot * tf.log(hypothesis1)) / len(hypothesis1)
    grads = tape.gradient(cost, [w0,w1,b0,b1])
    optimizer.apply_gradients(grads_and_vars = zip(grads, [w0,w1,b0,b1]))
    if step % 100 == 0:
        print(f"step: {step}, cost : {cost.numpy()}")

step: 0, cost : 1.9632397890090942
step: 100, cost : 0.04954873025417328
step: 200, cost : 0.044651761651039124
step: 300, cost : 0.04102938994765282
step: 400, cost : 0.026095466688275337
step: 500, cost : 0.012352947145700455
step: 600, cost : 0.006813612766563892
step: 700, cost : 0.004427868407219648
step: 800, cost : 0.003175326157361269
step: 900, cost : 0.002413754118606448
step: 1000, cost : 0.001903844648040831


In [25]:
X_test =scaler.transform(X_test)
X_test

array([[-1.2337222 ,  0.06672578, -1.1678654 , -1.2657381 ],
       [-0.37583584, -1.5346977 ,  0.02460665, -0.21004   ],
       [ 0.11438511, -0.16204883,  0.81958795,  0.84565806],
       [ 0.48205042, -0.39082348,  0.36531302,  0.18584672],
       [-1.3562778 ,  0.2955009 , -1.3382186 , -1.2657381 ],
       [ 0.72716117, -0.84837323,  0.93315685,  0.97762036],
       [ 2.3203785 , -0.16204883,  1.3874317 ,  1.5054693 ],
       [-1.111167  , -1.5346977 , -0.20253094, -0.21004   ],
       [ 1.0948265 , -0.16204883,  0.8763723 ,  1.5054693 ],
       [ 2.3203785 ,  1.6681497 ,  1.728138  ,  1.3735073 ],
       [ 0.8497163 , -0.16204883,  1.2170788 ,  1.3735073 ],
       [-1.111167  ,  0.06672578, -1.2246498 , -1.3977003 ],
       [-0.00816999, -0.84837323,  0.81958795,  0.97762036],
       [ 0.48205042, -1.9922473 ,  0.47888166,  0.4497713 ],
       [-0.13072567, -0.39082348,  0.30852842,  0.18584672],
       [-0.25328076, -1.305923  ,  0.13817544, -0.0780777 ],
       [ 1.0948265 ,  0.

In [26]:
hypothesis0 = tf. sigmoid(tf.matmul(X_test, w0) + b0)

In [27]:
predict = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
predict

<tf.Tensor: id=82239, shape=(30, 3), dtype=float32, numpy=
array([[9.99774992e-01, 2.24989039e-04, 4.32110649e-17],
       [2.22854233e-05, 9.99977708e-01, 3.77558180e-08],
       [1.25621624e-09, 6.28012049e-06, 9.99993682e-01],
       [1.59568226e-05, 9.99953032e-01, 3.10288669e-05],
       [9.99796212e-01, 2.03865813e-04, 3.79062960e-17],
       [1.78529771e-13, 2.36951403e-10, 1.00000000e+00],
       [9.64274559e-13, 6.89697188e-10, 1.00000000e+00],
       [1.48895837e-03, 9.98510897e-01, 7.89452059e-08],
       [9.23341481e-13, 7.24590832e-10, 1.00000000e+00],
       [2.19899446e-11, 9.97350114e-09, 1.00000000e+00],
       [4.42999968e-15, 2.10022017e-12, 1.00000000e+00],
       [9.99782741e-01, 2.17261681e-04, 4.03977839e-17],
       [3.16328030e-09, 4.16659866e-04, 9.99583304e-01],
       [1.11429230e-07, 9.99857068e-01, 1.42742501e-04],
       [2.38039161e-06, 9.99997616e-01, 8.99813946e-10],
       [4.43030467e-06, 9.99995589e-01, 1.73494037e-08],
       [1.09444634e-10, 1.097

In [28]:
predict01 = tf.argmax(predict,1)
predict01

<tf.Tensor: id=82241, shape=(30,), dtype=int64, numpy=
array([0, 1, 2, 1, 0, 2, 2, 1, 2, 2, 2, 0, 2, 1, 1, 1, 2, 2, 0, 2, 0, 2,
       2, 1, 0, 2, 2, 0, 1, 1], dtype=int64)>

In [29]:
target = tf.argmax(y_test_onehot, 1)
target

<tf.Tensor: id=82244, shape=(30,), dtype=int64, numpy=
array([0, 1, 2, 1, 0, 2, 2, 1, 2, 2, 2, 0, 2, 1, 1, 1, 2, 2, 0, 2, 0, 2,
       2, 1, 0, 2, 2, 0, 1, 1], dtype=int64)>

In [31]:
acc = tf.reduce_mean(tf.cast(tf.equal(predict01, target), dtype = tf.float32))
acc.numpy()

1.0