In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import keras
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [2]:
print(keras.__version__)

2.2.5


In [3]:
from google.colab import drive

drive.mount('gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at gdrive


In [ ]:
#학습 데이터의 경로
TRAIN_DIR = './gdrive/My Drive/ai/workspace/data/dental_image/train/'
#테스트 데이터의 경로
TEST_DIR = './gdrive/My Drive/ai/workspace/data/dental_image/test/'

In [ ]:
#이미지의 가로 세로
IM_WIDTH = 220
IM_HEIGHT = 220

In [ ]:
#학습에 사용될 이미지를 읽을 객체

# 실행할때마다 변형된 이미지를 리턴해서 
#이미지가 많은것 같은 효과를 줌
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
      rotation_range=180, # 회전 쵀대 180도
      width_shift_range=0.2, # 좌우 이동 최대 이미지 가로사이즈 20%
      height_shift_range=0.2, # 상하 이동 최대 이미지  세로사이즈 20%
      horizontal_flip=True, # 좌우 반전 실행
      vertical_flip=True # 상하 반전 실행 
      )

In [ ]:
#train_datagen.flow_from_directory() : 디렉토리에서 이미지를 읽을 객체를 생성
#train_datagen.flow_from_directory(
#        이미지 경로,       : TRAIN_DIR (/dental_image/train/)
#        target_size=(이미지가로, 이미지세로), IM_WIDTH (220) x IM_HEIGHT(220)
#        batch_size=한번에 리턴할 이미지의 개수, 50개
#        class_mode=분류방법, categorical (다중분류) binary(0 1 로 이중 분류)
#        shuffle=이미지를 섞을 여부
#)
        
train_generator = train_datagen.flow_from_directory(
         TRAIN_DIR,
        target_size=(IM_WIDTH, IM_HEIGHT),
        batch_size=8,
        class_mode='categorical',
        shuffle=True)

Found 150 images belonging to 3 classes.


In [ ]:
# 검증에 사용될 이미지를 읽을 객체
#테스트에서는 이미지를 변형 할 필요가 없으므로
#ImageDataGenerator에 값을 주지 않음
#이미지가 변형되지 않고 같은 이미지 리턴
test_datagen = ImageDataGenerator(rescale=1.0/255)

In [ ]:
#test_datagen.flow_from_directory() : 디렉토리에서 이미지를 읽을 객체를 생성
#test_datagen.flow_from_directory(
#        이미지 경로,       : TEST_DIR (/dental_image/test/)
#        target_size=(이미지가로, 이미지세로), IM_WIDTH (220) x IM_HEIGHT(220)
#        batch_size=한번에 리턴할 이미지의 개수, 10개
#        class_mode=분류방법, categorical (다중분류) binary(0 1 로 이중 분류)
#        shuffle=이미지를 섞을 여부 False 섞지 않음
#)
        
test_generator = test_datagen.flow_from_directory(
        TEST_DIR,
        target_size=(IM_WIDTH, IM_HEIGHT),
        batch_size=60,
        class_mode='categorical',
        shuffle=False)

Found 60 images belonging to 3 classes.


In [ ]:
#학습데이터의 전체 이미지 개수를 리턴
train_generator.n

150

In [ ]:
#한번에 리턴할 이미지의 개수 
train_generator.batch_size

8

In [ ]:
#테스트 데이터의 전체 이미지 개수를 리턴
test_generator.n

60

In [ ]:
#train_generator.next()
#train_generator.batch_size 에 설정된 이미지 50개를 리턴해서 img에 대입
#이지지의 label을 label에 대입
img, label = train_generator.next()

In [ ]:
img

array([[[[0.4453585 , 0.13555457, 0.10810359],
         [0.44705886, 0.13725491, 0.10980393],
         [0.44705886, 0.13725491, 0.10980393],
         ...,
         [0.5433219 , 0.26881206, 0.23174179],
         [0.5416029 , 0.26709312, 0.22830385],
         [0.5411765 , 0.26666668, 0.227451  ]],

        [[0.44449902, 0.1346951 , 0.10724412],
         [0.44705886, 0.13725491, 0.10980393],
         [0.44705886, 0.13725491, 0.10980393],
         ...,
         [0.5411765 , 0.26666668, 0.227451  ],
         [0.5411765 , 0.26666668, 0.227451  ],
         [0.54007465, 0.26556486, 0.22634916]],

        [[0.44363958, 0.13383563, 0.10638463],
         [0.44705886, 0.13725491, 0.10980393],
         [0.44705886, 0.13725491, 0.10980393],
         ...,
         [0.5358601 , 0.2613503 , 0.22213462],
         [0.5341412 , 0.25963137, 0.22041567],
         [0.5328778 , 0.25836796, 0.21915227]],

        ...,

        [[0.38431376, 0.1254902 , 0.07144015],
         [0.38431376, 0.1254902 , 0.07058824]

In [ ]:
img.shape

(50, 220, 220, 3)

In [ ]:
label

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
label.shape

(50, 3)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D,MaxPooling2D
from keras.optimizers import Adam

In [ ]:
from keras.applications.resnet50 import ResNet50

#Resnet50 구조를 갖는 Model생성
conv_layers = ResNet50(weights='imagenet', include_top=False, input_shape=(IM_WIDTH, IM_HEIGHT, 3))

/usr/local/lib/python3.6/dist-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


94658560/94653016 [==============================] - 2s 0us/step


In [ ]:
conv_layers.summary()

Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 220, 220, 3)  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 226, 226, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 110, 110, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 110, 110, 64) 256         conv1[0][0]                      
___________________________________________________________________________________________

In [ ]:
#입력값을 읽어서 예측을 할 Sequential 객체 생성
model = Sequential()

In [ ]:
#Resnet50대입
model.add(conv_layers)

In [ ]:
#선형 회귀를 하기 위해서 합성곱 연산을 수행한 결과를 1차원 배열로 변환
model.add(Flatten())

In [ ]:
#Dense : 선형 회귀를 수행할 객체
#Dense(출력데이터의 칸의수) : 출력 데이터는 y_h1이고 칸의 수는 512 이므로
#Dense(512)  
# activation="relu" :선형 회귀 후 relu 활성 함수 사용
#model.add(Dense(512, activation='relu')) :Dense 모델을 예측 할 수 있도록 model에 추가
model.add(Dense(512, activation='relu'))

In [ ]:
#Dense : 선형 회귀를 수행할 객체
#Dense(출력데이터의 칸의수) : 출력 데이터 칸의 수는 3이므로
#Dense(3)

#Dense(3) : 선형 회귀를 할 객체를 생성  출력 칸수는 3
    
# activation="softmax" :선형 회귀 후 softmax 함수를 활성 함수를 이용해서 0~1사이 값을 리턴  
    
    
#model.add(Dense(3, activation="softmax")):Dense 모델을 예측 할 수 있도록 model에 추가
model.add(Dense(3, activation='softmax'))

In [ ]:
#생성된 모델 정보 출력
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
resnet50 (Model)             (None, 7, 7, 2048)        23587712  
_________________________________________________________________
flatten_1 (Flatten)          (None, 100352)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               51380736  
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 1539      
Total params: 74,969,987
Trainable params: 74,916,867
Non-trainable params: 53,120
_________________________________________________________________


In [ ]:
#GradientDecnet를 이용해서 w0,b0와 w1,b1를 찾는 방법을 설정함
#loss='categorical_crossentropy' : -(y * tf.log(hypothesis1)) 합 이 최소가 되는 w1,w2,w3,w4 를 찾음
#optimizer=Adam(lr=1e-4) : learning rate를 0.00001 로 설정
model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=1e-4),metrics=['acc'])

In [ ]:
#model.fit(train_generator ,epochs=15) :train_generator 를 이용해서 이미지를 리턴 받음 (epach를 진행할때 마다 증강된 이미지 리턴)
#                                       epochs=15 - 50개씩 3번 150개 이미지를 15번 반복해서 학습
model.fit(train_generator , epochs=15)

Epoch 1/15
19/19 [==============================] - 3s 161ms/step - loss: 0.2086 - acc: 0.9342
Epoch 2/15
19/19 [==============================] - 3s 166ms/step - loss: 0.2110 - acc: 0.9210
Epoch 3/15
19/19 [==============================] - 3s 162ms/step - loss: 0.2685 - acc: 0.9387
Epoch 4/15
19/19 [==============================] - 3s 160ms/step - loss: 0.1651 - acc: 0.9408
Epoch 5/15
19/19 [==============================] - 3s 158ms/step - loss: 0.3072 - acc: 0.9144
Epoch 6/15
19/19 [==============================] - 3s 167ms/step - loss: 0.1729 - acc: 0.9210
Epoch 7/15
19/19 [==============================] - 3s 157ms/step - loss: 0.2705 - acc: 0.9210
Epoch 8/15
19/19 [==============================] - 3s 168ms/step - loss: 0.3964 - acc: 0.8950
Epoch 9/15
19/19 [==============================] - 3s 160ms/step - loss: 0.2492 - acc: 0.9189
Epoch 10/15
19/19 [==============================] - 3s 159ms/step - loss: 0.1163 - acc: 0.9671
Epoch 11/15
19/19 [==============================

In [ ]:
#test_generator.next()
#test_generator.batch_size 에 설정된 이미지 60개를 리턴해서 X_test에 대입
#이미지의 label을 y_test에 대입
X_test,y_test = test_generator.next()

In [ ]:
X_test

array([[[[0.90196085, 0.8352942 , 0.7176471 ],
         [0.9176471 , 0.8352942 , 0.72156864],
         [0.9294118 , 0.8352942 , 0.7254902 ],
         ...,
         [0.7686275 , 0.5647059 , 0.5803922 ],
         [0.77647066, 0.57254905, 0.5882353 ],
         [0.7725491 , 0.5686275 , 0.58431375]],

        [[0.91372555, 0.8313726 , 0.7254902 ],
         [0.92549026, 0.8313726 , 0.7294118 ],
         [0.9294118 , 0.8352942 , 0.73333335],
         ...,
         [0.8745099 , 0.67058825, 0.6862745 ],
         [0.86666673, 0.6627451 , 0.6784314 ],
         [0.8470589 , 0.6509804 , 0.6627451 ]],

        [[0.909804  , 0.8235295 , 0.7294118 ],
         [0.9215687 , 0.82745105, 0.7254902 ],
         [0.9215687 , 0.82745105, 0.7254902 ],
         ...,
         [0.854902  , 0.65882355, 0.67058825],
         [0.85098046, 0.654902  , 0.6666667 ],
         [0.8470589 , 0.6509804 , 0.6627451 ]],

        ...,

        [[0.49803925, 0.24705884, 0.2392157 ],
         [0.48627454, 0.23529413, 0.227451  ]

In [ ]:
y_test

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [ ]:
# model.predict(X_test) : 
#X_test가 어떤 이미지인지 분류
predict =model.predict(X_test)
predict

array([[1.00000000e+00, 1.41867389e-25, 1.51820787e-29],
       [8.79977763e-01, 7.25011677e-02, 4.75209728e-02],
       [3.10425013e-01, 3.62937062e-05, 6.89538717e-01],
       [9.99956846e-01, 7.04784634e-06, 3.60855738e-05],
       [1.00000000e+00, 7.10565352e-17, 4.29791214e-16],
       [2.50130501e-02, 2.22806364e-01, 7.52180576e-01],
       [9.88855809e-02, 2.82516400e-03, 8.98289263e-01],
       [1.00000000e+00, 6.36591706e-18, 3.58980570e-17],
       [1.00000000e+00, 2.60869126e-12, 5.58165493e-13],
       [9.94871497e-01, 1.72665474e-04, 4.95588034e-03],
       [9.99997020e-01, 2.95569885e-06, 3.79211301e-10],
       [1.00000000e+00, 4.33149529e-13, 2.76673888e-12],
       [5.88456984e-04, 3.71339649e-01, 6.28071904e-01],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.51265289e-03, 2.24381685e-02, 9.75049138e-01],
       [1.00000000e+00, 1.41883781e-23, 1.77437580e-14],
       [1.00000000e+00, 1.06920849e-20, 2.11925977e-10],
       [1.00000000e+00, 4.50352

In [ ]:
#np.argmax(predict,1) : predict 최대값의 인덱스를 리턴
#                  1: 각 줄에서 최대 값의 인덱스를 리턴
predict01 = np.argmax(predict,1)
predict01

array([0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0])

In [ ]:
#np.argmax(y_test,1) : y_test 최대값의 인덱스를 리턴
#                  1: 각 줄에서 최대 값의 인덱스를 리턴
target = np.argmax(y_test, 1)
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#predict01 == target 가 같으면 true 다르면 false 리턴
predict02 = (predict01 == target)
predict02

array([ True,  True, False,  True,  True, False, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False])

In [ ]:
#True는 1로 False는 0으로 변환 해서 합을 계산
np.sum(predict02)

48

In [ ]:
#정확도를 계산
#len(predict02) : redict02의 줄의 수를 리턴
acc=np.sum(predict02)/len(predict02)
acc

0.8

In [ ]:
#레이블의 이름을 리턴
train_generator.class_indices.keys()

dict_keys(['cured', 'decayed', 'healthy'])

In [ ]:
##레이블의 이름을 리스트로 변환해서 custom_labels에 대입
custom_labels = list(train_generator.class_indices.keys())
custom_labels

['cured', 'decayed', 'healthy']

In [ ]:
custom_labels[0]

'cured'

In [ ]:
custom_labels[1]

'decayed'

In [ ]:
custom_labels[2]

'healthy'

In [ ]:
#이미지를 출력할 객체
fig = plt.figure(figsize=(20,60))
for i in range(60):
    #4줄 5칸으로 나누고 i+1번째 이미지를 그림
    subplot = fig.add_subplot(12, 5, i + 1)
    
    #subplot.set_xticks([]) : 그래프의 x축을 설정 
    #데이터가 없으므로 x축에 아무 데이터도 출력 안됨
    subplot.set_xticks([])
    
    #subplot.set_yticks([]) : 그래프의 y축을 설정 
    #데이터가 없으므로 y축에 아무 데이터도 출력 안됨
    subplot.set_yticks([])
    #예측값(숫자)을 predict_num에 대입
    predict_num=predict01[i]
    #예측값에 해당하는 문자를 리턴
    predict_str=custom_labels[predict_num]
    #실제 값(숫자) 리턴
    target_num=target[i]
    #실제 값에 해당하는 문자 리턴
    target_str=custom_labels[target_num]
    #이미지의 제목으로 예측한 이미지의 이름, 실제 이름 출력
    subplot.set_title('predict: %s, target:%s' % (predict_str,target_str))
    #X_test[i]를 255로 나눠서 0~1 사이 범위로 변환
    #X_test[i]=X_test[i]/255.0
    #이미지 출력
    subplot.imshow(X_test[i].reshape((220, 220,3)),
                   cmap=plt.cm.gray_r)
#그래프를 화면에 그림
plt.show()

Output hidden; open in https://colab.research.google.com to view.