In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
X = np.array(
    [
        [0, 0],
        [1, 0],
        [1, 1],
        [0, 0],
        [0, 1]
    ], dtype = 'float32')
X

array([[0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.]], dtype=float32)

In [3]:
y = np.array([
    [1, 0, 0], # 기타
    [0, 1, 0], # 포유류
    [0, 0, 1], # 조류
    [1, 0, 0], # 기타
    [0, 0, 1] # 조류
], dtype ='float32')
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [4]:
initializer = tf.contrib.layers.xavier_initializer()

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [5]:
w0 = tf.Variable(initializer([2,10]))
w0

<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.23375535,  0.2513417 , -0.646504  ,  0.43313485, -0.6089591 ,
         0.63811916, -0.3882839 ,  0.484402  , -0.3993746 ,  0.52930254],
       [-0.23909941,  0.3395719 , -0.6978975 ,  0.3692271 ,  0.27884555,
         0.2699932 ,  0.20424294,  0.584812  , -0.00718588, -0.4672354 ]],
      dtype=float32)>

In [6]:
b0 = tf.Variable(initializer([10]))
b0

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([-0.02484357,  0.39788914,  0.2067017 , -0.36099392, -0.37103963,
       -0.38725907, -0.07433823, -0.42234915,  0.2934333 ,  0.1627199 ],
      dtype=float32)>

In [7]:
w1 = tf.Variable(initializer([10,3]))
b1 = tf.Variable(initializer([3]))

In [8]:
tf.matmul(X, w0) + b0

<tf.Tensor: id=61, shape=(5, 10), dtype=float32, numpy=
array([[-0.02484357,  0.39788914,  0.2067017 , -0.36099392, -0.37103963,
        -0.38725907, -0.07433823, -0.42234915,  0.2934333 ,  0.1627199 ],
       [ 0.20891178,  0.64923084, -0.4398023 ,  0.07214093, -0.9799987 ,
         0.2508601 , -0.46262214,  0.06205285, -0.1059413 ,  0.69202244],
       [-0.03018764,  0.98880273, -1.1376998 ,  0.44136804, -0.70115316,
         0.5208533 , -0.2583792 ,  0.64686483, -0.11312717,  0.22478706],
       [-0.02484357,  0.39788914,  0.2067017 , -0.36099392, -0.37103963,
        -0.38725907, -0.07433823, -0.42234915,  0.2934333 ,  0.1627199 ],
       [-0.263943  ,  0.73746103, -0.4911958 ,  0.00823319, -0.09219408,
        -0.11726588,  0.12990472,  0.16246283,  0.28624743, -0.30451548]],
      dtype=float32)>

In [9]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
hypothesis0

<tf.Tensor: id=67, shape=(5, 10), dtype=float32, numpy=
array([[0.49378943, 0.59818035, 0.5514922 , 0.410719  , 0.40828985,
        0.4043773 , 0.481424  , 0.39595476, 0.57283646, 0.54059047],
       [0.5520388 , 0.6568371 , 0.3917881 , 0.5180274 , 0.27289206,
        0.5623882 , 0.38636398, 0.51550823, 0.4735394 , 0.66641665],
       [0.49245366, 0.7288514 , 0.2427429 , 0.60858494, 0.33155662,
        0.6273473 , 0.43576217, 0.6563036 , 0.47174832, 0.5559613 ],
       [0.49378943, 0.59818035, 0.5514922 , 0.410719  , 0.40828985,
        0.4043773 , 0.481424  , 0.39595476, 0.57283646, 0.54059047],
       [0.4343947 , 0.67644036, 0.3796119 , 0.50205827, 0.47696778,
        0.47071707, 0.5324306 , 0.5405266 , 0.5710772 , 0.42445397]],
      dtype=float32)>

In [10]:
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1) + b1)
hypothesis1

<tf.Tensor: id=72, shape=(5, 3), dtype=float32, numpy=
array([[0.26616594, 0.51641816, 0.2174159 ],
       [0.31019855, 0.4598472 , 0.22995436],
       [0.29800832, 0.45675814, 0.24523363],
       [0.26616594, 0.51641816, 0.2174159 ],
       [0.25263393, 0.51582646, 0.23153964]], dtype=float32)>

In [11]:
cost = -tf.reduce_sum(y * tf.log(hypothesis1))/len(hypothesis1)
cost

<tf.Tensor: id=80, shape=(), dtype=float32, numpy=1.258536>

In [12]:
optimizer = tf.train.AdamOptimizer(0.01)

In [13]:
for step in range(1001):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
        hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
        # print(len(hypothesis1))
        #cost = -tf.reduce_sum(y * tf.log(hypothesis1))/len(hypothesis1)
        cost = sum(y * -tf.log(hypothesis1))/len(hypothesis1)
        grads = tape.gradient(cost, [w0,w1,b0,b1])
        optimizer.apply_gradients(grads_and_vars = zip(grads, [w0,w1,b0,b1]))
        if step % 100 == 0:
            print(f"step: {step}, cost: {cost.numpy()}")

step: 0, cost: [0.5294541 0.1553722 0.5737096]
step: 100, cost: [0.08780887 0.19467884 0.09656519]
step: 200, cost: [0.01981974 0.03740616 0.01723128]
step: 300, cost: [0.00682408 0.01199497 0.00592521]
step: 400, cost: [0.00351411 0.00599303 0.00306045]
step: 500, cost: [0.00218215 0.00365062 0.00190324]
step: 600, cost: [0.00150288 0.00247872 0.00131172]
step: 700, cost: [0.00110488 0.00180188 0.00096475]
step: 800, cost: [0.00084967 0.00137267 0.00074201]
step: 900, cost: [0.00067515 0.00108202 0.00058963]
step: 1000, cost: [0.00054998 0.0008753  0.00048033]


In [14]:
w0

<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.67416656,  3.4782164 , -3.377148  , -1.7115091 , -0.56376535,
         3.4110737 , -3.043545  ,  0.09667139, -1.934479  , -0.31189898],
       [-2.5839515 ,  2.026653  , -2.4576354 ,  3.0627525 ,  3.4795635 ,
         1.7297877 , -1.6178144 ,  2.7178783 ,  2.3705947 , -2.9939437 ]],
      dtype=float32)>

In [15]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
predict = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
predict

<tf.Tensor: id=122301, shape=(5, 3), dtype=float32, numpy=
array([[9.9862874e-01, 1.0916844e-03, 2.7968475e-04],
       [2.1012118e-03, 9.9564183e-01, 2.2570624e-03],
       [1.1314389e-05, 1.5900508e-03, 9.9839860e-01],
       [9.9862874e-01, 1.0916844e-03, 2.7968475e-04],
       [6.5794500e-04, 1.3607083e-04, 9.9920601e-01]], dtype=float32)>

In [16]:
predict01 = tf.argmax(predict, 1)
predict01

<tf.Tensor: id=122303, shape=(5,), dtype=int64, numpy=array([0, 1, 2, 0, 2], dtype=int64)>

In [17]:
target = tf.argmax(y, 1)
target

<tf.Tensor: id=122306, shape=(5,), dtype=int64, numpy=array([0, 1, 2, 0, 2], dtype=int64)>

In [18]:
acc = tf.reduce_mean(tf.cast(tf.equal(predict01, target), dtype = tf.float32))
acc

<tf.Tensor: id=122310, shape=(), dtype=float32, numpy=1.0>