## 일차원 합성곱

In [1]:
import numpy as np

In [2]:
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])
x

array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [3]:
w = np.array([3, 5, 1, 2])
w

array([3, 5, 1, 2])

In [6]:
print('all x: ',x)
for i in range(6):
    print(f'x[{i} : {i+4}] = {x[i:i+4]}')

all x:  [2 8 3 7 1 2 0 4 5]
x[0 : 4] = [2 8 3 7]
x[1 : 5] = [8 3 7 1]
x[2 : 6] = [3 7 1 2]
x[3 : 7] = [7 1 2 0]
x[4 : 8] = [1 2 0 4]
x[5 : 9] = [2 0 4 5]


In [7]:
np.dot(x[0:4], w)

63

In [8]:
for i in range(6):
    print(np.dot(x[i:i+4], w))

63
48
49
28
21
20


In [9]:
from scipy.signal import correlate
correlate(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

In [11]:
correlate(x, w, mode='same')

array([18, 24, 63, 48, 49, 28, 21, 20, 25])

## 이차원 합성곱

In [12]:
import numpy as np

In [30]:
x = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [31]:
w = np.array([
                [2, 0],
                [0, 0]
             ])

In [15]:
from scipy.signal import correlate2d
correlate2d(x, w, mode='valid')

array([[ 2,  4],
       [ 8, 10]])

In [16]:
correlate2d(x, w, mode='same')

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## 텐서 플로를 이용한 이미지 합성곱

In [18]:
import tensorflow as tf
tf.enable_eager_execution()

In [32]:
x = np.array(x, dtype='float32')
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

![x](./img/그림3.png)

In [33]:
x = x.reshape(1, 3, 3, 1)
x

array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]], dtype=float32)

![w](./img/그림2.png)

In [37]:
w = w.reshape(2, 2, 1, 1)
w

array([[[[2]],

        [[0]]],


       [[[0]],

        [[0]]]])

In [38]:
conv = tf.nn.conv2d(x, w, strides=1, padding='SAME')
conv

<tf.Tensor: id=9, shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[ 2.],
         [ 4.],
         [ 6.]],

        [[ 8.],
         [10.],
         [12.]],

        [[14.],
         [16.],
         [18.]]]], dtype=float32)>

In [39]:
tf.nn.max_pool2d(conv, ksize=2, strides=1, padding='VALID')

<tf.Tensor: id=10, shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[10.],
         [12.]],

        [[16.],
         [18.]]]], dtype=float32)>

In [40]:
def relu(x):
    return np.maximum(x,0)

In [41]:
relu(x)

array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]], dtype=float32)

In [43]:
tf.nn.relu(x)

<tf.Tensor: id=12, shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]], dtype=float32)>