## 문제 1. iris 데이터

In [1]:
# iris 데이터
import numpy as np
# 머신러닝
from sklearn.datasets import load_iris

data = load_iris()

features = data.data    # shape = (150, 4)
feature_names = data.feature_names
target = data.target
target_names = data.target_names

In [2]:
print(features.shape)
print(feature_names)
print(target_names)

(150, 4)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [3]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
target[:5]

array([0, 0, 0, 0, 0])

1. feature_names별 전체데이터에 대한 평균, 분산, 중위수, 4분위수, IQR을 구해보아라
2. target_name별로 따로 1번을 반복하라.

In [5]:
#평균, 분산, 중위수, 4분위수, IQR
[features[:,i].mean() for i in range(4)]

[5.843333333333334, 3.0573333333333337, 3.7580000000000005, 1.1993333333333336]

In [6]:
mean = [features[:,i].mean() for i in range(4)]
var = [features[:,i].var() for i in range(4)]

In [7]:
[np.percentile(features[:,i],100) for i in range(4)]
[np.percentile(features[:,i],75) for i in range(4)]
[np.median(features[:,i]) for i in range(4)]
[np.percentile(features[:,i],25) for i in range(4)]
[np.percentile(features[:,i],0) for i in range(4)]

[4.3, 2.0, 1.0, 0.1]

In [8]:
IQR = [np.percentile(features[:,i],75) - np.percentile(features[:,i],25) for i in range(4)]

In [9]:
# 강사님 코드

In [10]:
N = features.shape[0] # = len(features)
N

150

In [11]:
barX = features.sum(0, keepdims = True) / N # = features.mean(0, keepdims= True)
barX

array([[5.84333333, 3.05733333, 3.758     , 1.19933333]])

In [12]:
varX = np.power((features - barX), 2).sum(0, keepdims = True) / N # = features.var(0, keepdims= True)
varX

array([[0.68112222, 0.18871289, 3.09550267, 0.57713289]])

In [14]:
sl = np.sort(features[:,0]).reshape((N, -1))
sw = np.sort(features[:,0]).reshape((N, -1))
pl = np.sort(features[:,0]).reshape((N, -1))
pw = np.sort(features[:,0]).reshape((N, -1))

In [77]:
q2Idx = round(N/2)
q1Idx = round(N/4)
q3Idx = round(N*3/4)

In [78]:
sortedIris = np.hstack((sl,sw,pl,pw))

In [80]:
q1 = sortedIris[q1Idx, :]
q2 = sortedIris[q2Idx, :]
q3 = sortedIris[q3Idx, :]

In [82]:
IQR = q3 -q1 # = np.quantile(features, [.25, .5, .75], axis=0)
IQR

array([1.3, 1.3, 1.3, 1.3])

## 문제2. mtcars 데이터

In [115]:
# mtcars 데이터
import pandas as pd

cars = pd.read_csv('https://gist.githubusercontent.com/ZeccaLehn/4e06d2575eb9589dbe8c365d61cb056c/raw/64f1660f38ef523b2a1a13be77b002b98665cdfe/mtcars.csv')

cars.rename(columns={'Unnamed: 0':'brand'}, inplace=True)
cars

brand   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

1. cyl(실린더)별, 연비(mpg)의 평균과 중위값을 구하여라.
2. wt(무게)와 연비(mpg) 간의 상관계수를 구하여라.
3. cyl(실린더)와 기어(gear) 수간의 크로스 테이블을 구하여라.

In [176]:
dic2 = {i:[] for i in set(ndcar[:,2])}

In [181]:
for i in ndcar:
    dic2[i[2]].append(i[-2])

In [184]:
dic2[8]

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5]

{4, 6, 8}

In [189]:
dic2

{8: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5],
 4: [4, 4, 4, 4, 4, 4, 3, 4, 5, 5, 4],
 6: [4, 4, 3, 3, 4, 4, 5]}

In [202]:
dic2.values()

dict_values([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5], [4, 4, 4, 4, 4, 4, 3, 4, 5, 5, 4], [4, 4, 3, 3, 4, 4, 5]])

In [223]:
row = []
for i in set(ndcar[:,2]):
    col=[]
    for j in set(ndcar[:,-2]):
        col.append(dic2[i].count(j))
    col.append(sum(col))
    row += col
row

[12, 0, 2, 14, 1, 8, 2, 11, 2, 4, 1, 7]

In [227]:
k = np.array(row).reshape(3,4)
k

array([[12,  0,  2, 14],
       [ 1,  8,  2, 11],
       [ 2,  4,  1,  7]])

In [233]:
slst=[]
for c in range(np.shape(k)[1]):
    s = 0
    for r in range(np.shape(k)[0]):
        s += k[r][c]
    slst.append(s)
slst

[15, 12, 5, 32]

In [241]:
np.vstack((k,slst))

array([[12,  0,  2, 14],
       [ 1,  8,  2, 11],
       [ 2,  4,  1,  7],
       [15, 12,  5, 32]])

In [211]:
for i in k:
    sum(i)

14
11
7


In [180]:
for i in ndcar:
    print(i)

['Mazda RX4' 21.0 6 160.0 110 3.9 2.62 16.46 0 1 4 4]
['Mazda RX4 Wag' 21.0 6 160.0 110 3.9 2.875 17.02 0 1 4 4]
['Datsun 710' 22.8 4 108.0 93 3.85 2.32 18.61 1 1 4 1]
['Hornet 4 Drive' 21.4 6 258.0 110 3.08 3.215 19.44 1 0 3 1]
['Hornet Sportabout' 18.7 8 360.0 175 3.15 3.44 17.02 0 0 3 2]
['Valiant' 18.1 6 225.0 105 2.76 3.46 20.22 1 0 3 1]
['Duster 360' 14.3 8 360.0 245 3.21 3.57 15.84 0 0 3 4]
['Merc 240D' 24.4 4 146.7 62 3.69 3.19 20.0 1 0 4 2]
['Merc 230' 22.8 4 140.8 95 3.92 3.15 22.9 1 0 4 2]
['Merc 280' 19.2 6 167.6 123 3.92 3.44 18.3 1 0 4 4]
['Merc 280C' 17.8 6 167.6 123 3.92 3.44 18.9 1 0 4 4]
['Merc 450SE' 16.4 8 275.8 180 3.07 4.07 17.4 0 0 3 3]
['Merc 450SL' 17.3 8 275.8 180 3.07 3.73 17.6 0 0 3 3]
['Merc 450SLC' 15.2 8 275.8 180 3.07 3.78 18.0 0 0 3 3]
['Cadillac Fleetwood' 10.4 8 472.0 205 2.93 5.25 17.98 0 0 3 4]
['Lincoln Continental' 10.4 8 460.0 215 3.0 5.4239999999999995 17.82 0 0 3
 4]
['Chrysler Imperial' 14.7 8 440.0 230 3.23 5.345 17.42 0 0 3 4]
['Fiat 128' 32

In [179]:
dic2[ndcar[3,2]]

[]

In [170]:
set(ndcar[:,2])

{4, 6, 8}

In [171]:
set(ndcar[:,-2])

{3, 4, 5}

In [153]:
ndcar[:,6].mean()

3.2172499999999995

In [154]:
ndcar[:,1].mean()

20.090624999999996

In [242]:
# 공분산 = (x편차 * y편차) 의 평균
cov = ((ndcar[:,6]- ndcar[:,6].mean()) * (ndcar[:,1]- ndcar[:,1].mean())).mean()
cov

-4.95678828125

In [169]:
# 상관계수 = 공분산(cov) / sqrt( x분산 * y분산 )
cov / (((ndcar[:,6]- ndcar[:,6].mean())**2).mean() * ((ndcar[:,1]- ndcar[:,1].mean())**2).mean())**(1/2)

-0.8676593765172278

In [121]:
ndcar[:,2]

array([6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8,
       8, 8, 8, 4, 4, 4, 8, 6, 8, 4], dtype=object)

In [122]:
for i in set(ndcar[:,2]):
        print(i)

8
4
6


In [120]:
set(ndcar[:,2])

{4, 6, 8}

In [131]:
a= np.array([1,2])

In [132]:
a

array([1, 2])

In [138]:
dic = {i:[] for i in set(ndcar[:,2])}

In [139]:
dic

{8: [], 4: [], 6: []}

In [140]:
for _ in range(ndcar.shape[0]):
    for i in set(ndcar[:,2]):
        if ndcar[_,2] == i:
            dic[i].append(ndcar[_,1])

In [141]:
dic

{8: [18.7,
  14.3,
  16.4,
  17.3,
  15.2,
  10.4,
  10.4,
  14.7,
  15.5,
  15.2,
  13.3,
  19.2,
  15.8,
  15.0],
 4: [22.8, 24.4, 22.8, 32.4, 30.4, 33.9, 21.5, 27.3, 26.0, 30.4, 21.4],
 6: [21.0, 21.0, 21.4, 18.1, 19.2, 17.8, 19.7]}

In [147]:
for i in dic:
    print(i,sum(dic[i])/len(dic[i]))

8 15.100000000000003
4 26.663636363636364
6 19.74285714285714


In [148]:
for i in dic:
    dic[i].sort()
    

In [151]:
for i in dic:
    print(dic[i][round(len(dic[i])/2)])

15.2
27.3
21.0


In [149]:
dic

{8: [10.4,
  10.4,
  13.3,
  14.3,
  14.7,
  15.0,
  15.2,
  15.2,
  15.5,
  15.8,
  16.4,
  17.3,
  18.7,
  19.2],
 4: [21.4, 21.5, 22.8, 22.8, 24.4, 26.0, 27.3, 30.4, 30.4, 32.4, 33.9],
 6: [17.8, 18.1, 19.2, 19.7, 21.0, 21.0, 21.4]}

In [116]:
ndcar = cars.values # cars.to_numpy()
ndcar

array([['Mazda RX4', 21.0, 6, 160.0, 110, 3.9, 2.62, 16.46, 0, 1, 4, 4],
       ['Mazda RX4 Wag', 21.0, 6, 160.0, 110, 3.9, 2.875, 17.02, 0, 1, 4,
        4],
       ['Datsun 710', 22.8, 4, 108.0, 93, 3.85, 2.32, 18.61, 1, 1, 4, 1],
       ['Hornet 4 Drive', 21.4, 6, 258.0, 110, 3.08, 3.215, 19.44, 1, 0,
        3, 1],
       ['Hornet Sportabout', 18.7, 8, 360.0, 175, 3.15, 3.44, 17.02, 0,
        0, 3, 2],
       ['Valiant', 18.1, 6, 225.0, 105, 2.76, 3.46, 20.22, 1, 0, 3, 1],
       ['Duster 360', 14.3, 8, 360.0, 245, 3.21, 3.57, 15.84, 0, 0, 3, 4],
       ['Merc 240D', 24.4, 4, 146.7, 62, 3.69, 3.19, 20.0, 1, 0, 4, 2],
       ['Merc 230', 22.8, 4, 140.8, 95, 3.92, 3.15, 22.9, 1, 0, 4, 2],
       ['Merc 280', 19.2, 6, 167.6, 123, 3.92, 3.44, 18.3, 1, 0, 4, 4],
       ['Merc 280C', 17.8, 6, 167.6, 123, 3.92, 3.44, 18.9, 1, 0, 4, 4],
       ['Merc 450SE', 16.4, 8, 275.8, 180, 3.07, 4.07, 17.4, 0, 0, 3, 3],
       ['Merc 450SL', 17.3, 8, 275.8, 180, 3.07, 3.73, 17.6, 0, 0, 3, 3],
      

In [110]:
mean_cyl = ndcar[:,2] ==

In [111]:
mean_mpg = ndcar[:,1].sum()

In [113]:
a=np.sort(ndcar[:,2]).
a

In [3]:
arr = np.arange(20).reshape((5, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
# 점색인(point indexing) -> 차원 축소
arr[2,:2]

array([8, 9])

In [20]:
arr[2:3,:2]

array([[8, 9]])

In [4]:
# 불연속 색인(fancy index)
# 연속 색인
arr[[0,3],:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [9]:
arr[[0,-1], -2:]

array([[ 2,  3],
       [18, 19]])

In [12]:
arr[[0,3],[0,2]]

array([ 0, 14])

In [13]:
arr[[0,3],:][:,[0,2]]

array([[ 0,  2],
       [12, 14]])