In [1]:
from math import e

In [2]:
e

2.718281828459045

In [3]:
e**-1

0.36787944117144233

In [4]:
e**0

1.0

In [5]:
1/(1+e**-(-5))

0.006692850924284857

In [6]:
1/(1+e**-(-2.5))

0.07585818002124356

In [8]:
1/(1+e**-(0))

0.5

In [9]:
1/(1+e**-(2.5))

0.9241418199787566

In [7]:
1/(1+e**-(5))

0.9933071490757153

In [11]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [12]:
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype = "float32")
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [14]:
y = np.array([
    [0],
    [0],
    [0],
    [1]
], dtype = "float32")
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [21]:
w = np.array([[1],
              [2]], dtype = "float32")
b= np.array([3], dtype="float32")
w

array([[1.],
       [2.]], dtype=float32)

In [28]:
type(b)

numpy.ndarray

In [23]:
X[3]

array([1., 1.], dtype=float32)

In [24]:
np.dot(X[3], w)[0]

3.0

In [25]:
np.dot(X,w)

array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)

In [26]:
np.dot(X,w)+b

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [35]:
def sigmoid2(h):
    return 1/(1+e**-(h))

def sigmoid(h):
    return 1/(1 + np.exp(-h)) 

In [36]:
hypothesis = np.dot(X,w)+b
hypothesis

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [37]:
hypothesis = sigmoid(np.dot(X,w)+b)
print(hypothesis)

hypothesis = sigmoid2(np.dot(X,w)+b)
print(hypothesis)

[[0.95257413]
 [0.9933072 ]
 [0.98201376]
 [0.9975274 ]]
[[0.95257413]
 [0.9933072 ]
 [0.98201376]
 [0.9975274 ]]


In [38]:
hypothesis-y  #이건 2차원 배열

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [39]:
X.T[0]  #이건 1차원 배열

array([0., 0., 1., 1.], dtype=float32)

In [55]:
X.T[0].reshape(1,4)  #원래는 이렇게 써야 된다 1 = row 4 = column

array([[0., 0., 1., 1.]], dtype=float32)

In [56]:
x1 = X.T[0].reshape(1,-1)  #줄만 쓰고하나는 생략 가능 생략 할 때는 -1을 써준다.
x2 = X.T[1].reshape(1,-1)  #줄만 쓰고하나는 생략 가능 생략 할 때는 -1을 써준다.

In [57]:
np.dot(x1, (hypothesis -y))

array([[0.9795412]], dtype=float32)

In [58]:
np.sum(np.dot(x1, (hypothesis -y)))

0.9795412

In [59]:
w1_gred = 1/4 * np.sum(np.dot(x1, (hypothesis -y)))
print("w_gred: " ,w1_gred )

w_gred:  0.24488529562950134


In [61]:
x_col_2d2 = X.T[1].reshape(1,-1)
x_col_2d2

array([[0., 1., 0., 1.]], dtype=float32)

In [62]:
np.dot(x_col_2d2, (hypothesis-y))

array([[0.9908346]], dtype=float32)

In [65]:
np.dot(x_col_2d2, (hypothesis-y))[0][0]

0.9908346

In [69]:
w2_gred = np.sum(np.dot(x_col_2d2, (hypothesis-y)))/4
w2_gred

0.24770864844322205

In [71]:
b_gred = np.sum(hypothesis-y)/4
b_gred

0.731355607509613

In [73]:
lr = 0.05

for i in range(1000):
    for j in range(2):
        hypothesis = sigmoid(np.dot(X,w)+b)
        print("hypothesis:" , hypothesis)
        
        cost = 1/4*(y *np.log(hypothesis) + (1-y) * np.log(1-hypothesis))
        print("cost:", cost)
        
        X_col_2d = X.T[j].reshape(1,-1)
        
        w_gred = 1/4*np.sum(np.dot(X_col_2d, (hypothesis-y)))
        print("w_{}gred:{}".format(j,w))
        
        b_gred = 1/4*np.sum(hypothesis-y)
        print("b{}_gred:{}".format(i,w_gred))
        
        w[j] = w[j] -lr * w_gred
        
        b = b-lr * b_gred
        print("b:{}". format(b))
        
        

hypothesis: [[0.20201112]
 [0.46990442]
 [0.28053126]
 [0.5772308 ]]
cost: [[-0.05641515]
 [-0.1586745 ]
 [-0.08231056]
 [-0.13737828]]
w_0gred:[[0.43194398]
 [1.2532438 ]]
b0_gred:-0.035559482872486115
b:[-1.3803929]
hypothesis: [[0.2009459]
 [0.4682555]
 [0.2795548]
 [0.5760485]]
cost: [[-0.05608166]
 [-0.15789805]
 [-0.0819715 ]
 [-0.13789086]]
w_1gred:[[0.43372196]
 [1.2532438 ]]
b0_gred:0.011075995862483978
b:[-1.386953]
hypothesis: [[0.19989464]
 [0.4664846 ]
 [0.2782355 ]
 [0.5743102 ]]
cost: [[-0.05575297]
 [-0.15706684]
 [-0.08151409]
 [-0.13864641]]
w_0gred:[[0.43372196]
 [1.25269   ]]
b1_gred:-0.03686358034610748
b:[-1.3934395]
hypothesis: [[0.19885921]
 [0.46487057]
 [0.27730396]
 [0.57317466]]
cost: [[-0.05542964]
 [-0.15631166]
 [-0.08119163]
 [-0.1391412 ]]
w_1gred:[[0.43556514]
 [1.25269   ]]
b1_gred:0.009511306881904602
b:[-1.3998672]
hypothesis: [[0.19783719]
 [0.46315372]
 [0.2760177 ]
 [0.5714849 ]]
cost: [[-0.05511092]
 [-0.15551087]
 [-0.08074708]
 [-0.1398793 ]]


 [0.5126906 ]]
cost: [[-0.02996836]
 [-0.10177696]
 [-0.05909577]
 [-0.16702068]]
w_1gred:[[0.73900044]
 [1.3725563 ]]
b98_gred:-0.03822045028209686
b:[-2.062916]
hypothesis: [[0.11275378]
 [0.33437827]
 [0.21016757]
 [0.51263523]]
cost: [[-0.02990818]
 [-0.10175843]
 [-0.05898362]
 [-0.16704768]]
w_0gred:[[0.73900044]
 [1.3744674 ]]
b99_gred:-0.06929929554462433
b:[-2.06504]
hypothesis: [[0.11254146]
 [0.33390567]
 [0.21039025]
 [0.51297027]]
cost: [[-0.02984836]
 [-0.10158101]
 [-0.05905412]
 [-0.16688435]]
w_1gred:[[0.7424654]
 [1.3744674]]
b99_gred:-0.03828101605176926
b:[-2.0671628]
hypothesis: [[0.11232963]
 [0.33385926]
 [0.21003784]
 [0.5129181 ]]
cost: [[-0.0297887 ]
 [-0.10156358]
 [-0.05894255]
 [-0.16690977]]
w_0gred:[[0.7424654]
 [1.3763814]]
b100_gred:-0.06926101446151733
b:[-2.069277]
hypothesis: [[0.11211899]
 [0.33338925]
 [0.21026172]
 [0.51325506]]
cost: [[-0.02972938]
 [-0.10138726]
 [-0.05901342]
 [-0.16674559]]
w_1gred:[[0.7459284]
 [1.3763814]]
b100_gred:-0.03833

b177_gred:-0.03853153437376022
b:[-2.3593946]
hypothesis: [[0.08632194]
 [0.30337366]
 [0.204678  ]
 [0.54259694]]
cost: [[-0.02256925]
 [-0.09037654]
 [-0.05725205]
 [-0.15284713]]
w_0gred:[[1.0020854]
 [1.5281106]]
b178_gred:-0.06318126618862152
b:[-2.3611066]
hypothesis: [[0.086187  ]
 [0.30301195]
 [0.20491362]
 [0.542956  ]]
cost: [[-0.02253233]
 [-0.09024675]
 [-0.05732613]
 [-0.15268175]]
w_1gred:[[1.0052445]
 [1.5281106]]
b178_gred:-0.038508012890815735
b:[-2.36282]
hypothesis: [[0.08605216]
 [0.30305675]
 [0.20463465]
 [0.54300857]]
cost: [[-0.02249545]
 [-0.09026281]
 [-0.05723843]
 [-0.15265754]]
w_0gred:[[1.0052445]
 [1.530036 ]]
b179_gred:-0.06308919191360474
b:[-2.3645294]
hypothesis: [[0.08591781]
 [0.3026958 ]
 [0.20486994]
 [0.5433672 ]]
cost: [[-0.0224587 ]
 [-0.09013338]
 [-0.05731239]
 [-0.15249248]]
w_1gred:[[1.008399]
 [1.530036]]
b179_gred:-0.03848424553871155
b:[-2.36624]
hypothesis: [[0.08578356]
 [0.30274087]
 [0.20459141]
 [0.54342014]]
cost: [[-0.02242198]
 

 [0.57828015]]
cost: [[-0.01701205]
 [-0.08135276]
 [-0.05599835]
 [-0.1369242 ]]
w_0gred:[[1.2712696]
 [1.6977693]]
b269_gred:-0.0552600622177124
b:[-2.654853]
hypothesis: [[0.06569052]
 [0.27746245]
 [0.20087725]
 [0.57858044]]
cost: [[-0.01698689]
 [-0.08124648]
 [-0.05606018]
 [-0.13679442]]
w_1gred:[[1.2740326]
 [1.6977693]]
b269_gred:-0.03598927706480026
b:[-2.6563857]
hypothesis: [[0.06559652]
 [0.27751595]
 [0.20063135]
 [0.5786455 ]]
cost: [[-0.01696174]
 [-0.08126498]
 [-0.05598327]
 [-0.1367663 ]]
w_0gred:[[1.2740326]
 [1.6995687]]
b270_gred:-0.055180780589580536
b:[-2.6579156]
hypothesis: [[0.06550281]
 [0.2772093 ]
 [0.20082854]
 [0.5789452 ]]
cost: [[-0.01693667]
 [-0.08115889]
 [-0.05604494]
 [-0.13663685]]
w_1gred:[[1.2767916]
 [1.6995687]]
b270_gred:-0.035961367189884186
b:[-2.6594467]
hypothesis: [[0.06540915]
 [0.2772628 ]
 [0.2005829 ]
 [0.57901025]]
cost: [[-0.0169116 ]
 [-0.08117741]
 [-0.05596812]
 [-0.13660878]]
w_0gred:[[1.2767916]
 [1.7013668]]
b271_gred:-0.05

hypothesis: [[0.05212175]
 [0.25800136]
 [0.19620016]
 [0.6068394 ]]
cost: [[-0.01338231]
 [-0.07460196]
 [-0.05460124]
 [-0.12487277]]
w_0gred:[[1.4904287]
 [1.844261 ]]
b353_gred:-0.0492401048541069
b:[-2.9020581]
hypothesis: [[0.05205192]
 [0.25773066]
 [0.19636542]
 [0.60708934]]
cost: [[-0.01336388]
 [-0.07451078]
 [-0.05465265]
 [-0.12476983]]
w_1gred:[[1.4928907]
 [1.844261 ]]
b353_gred:-0.03379499912261963
b:[-2.9034736]
hypothesis: [[0.05198212]
 [0.25778314]
 [0.19614212]
 [0.6071547 ]]
cost: [[-0.01334548]
 [-0.07452846]
 [-0.0545832 ]
 [-0.1247429 ]]
w_0gred:[[1.4928907]
 [1.8459508]]
b354_gred:-0.04917578771710396
b:[-2.904887]
hypothesis: [[0.05191251]
 [0.2575128 ]
 [0.19630702]
 [0.6074041 ]]
cost: [[-0.01332712]
 [-0.07443742]
 [-0.05463448]
 [-0.12464024]]
w_1gred:[[1.4953495]
 [1.8459508]]
b354_gred:-0.03377076983451843
b:[-2.9063013]
hypothesis: [[0.05184295]
 [0.25756526]
 [0.196084  ]
 [0.6074695 ]]
cost: [[-0.01330878]
 [-0.07445507]
 [-0.05456513]
 [-0.12461333]

 [1.9773812]]
b434_gred:-0.04451083391904831
b:[-3.1234398]
hypothesis: [[0.04215067]
 [0.24120975]
 [0.19136932]
 [0.63093823]]
cost: [[-0.0107662 ]
 [-0.06900747]
 [-0.05310324]
 [-0.11513682]]
w_1gred:[[1.6823027]
 [1.9773812]]
b434_gred:-0.031963005661964417
b:[-3.1247606]
hypothesis: [[0.04209738]
 [0.2412605 ]
 [0.191165  ]
 [0.63100284]]
cost: [[-0.01075229]
 [-0.06902421]
 [-0.05304008]
 [-0.11511122]]
w_0gred:[[1.6823027]
 [1.9789793]]
b435_gred:-0.04445803910493851
b:[-3.1260798]
hypothesis: [[0.04204421]
 [0.2410191 ]
 [0.19130479]
 [0.63121325]]
cost: [[-0.01073842]
 [-0.06894468]
 [-0.0530833 ]
 [-0.11502788]]
w_1gred:[[1.6845256]
 [1.9789793]]
b435_gred:-0.031941913068294525
b:[-3.1273997]
hypothesis: [[0.04199109]
 [0.2410698 ]
 [0.19110067]
 [0.63127774]]
cost: [[-0.01072456]
 [-0.06896137]
 [-0.0530202 ]
 [-0.11500234]]
w_0gred:[[1.6845256]
 [1.9805764]]
b436_gred:-0.04440539702773094
b:[-3.1287177]
hypothesis: [[0.0419381 ]
 [0.24082875]
 [0.19124019]
 [0.63148767]]
c

 [0.65290844]]
cost: [[-0.0086913 ]
 [-0.06407186]
 [-0.05130627]
 [-0.10657959]]
w_0gred:[[1.8624246]
 [2.1111293]]
b520_gred:-0.040388885885477066
b:[-3.3429394]
hypothesis: [[0.03412713]
 [0.22586478]
 [0.1856548 ]
 [0.6530864 ]]
cost: [[-0.00868076]
 [-0.06400218]
 [-0.05134274]
 [-0.10651145]]
w_1gred:[[1.864444 ]
 [2.1111293]]
b520_gred:-0.03026219829916954
b:[-3.3441734]
hypothesis: [[0.03408648]
 [0.22591357]
 [0.1854683 ]
 [0.65314966]]
cost: [[-0.00867024]
 [-0.06401794]
 [-0.05128549]
 [-0.10648724]]
w_0gred:[[1.864444 ]
 [2.1126423]]
b521_gred:-0.040345508605241776
b:[-3.345406]
hypothesis: [[0.03404592]
 [0.22569805]
 [0.18558685]
 [0.6533274 ]]
cost: [[-0.00865975]
 [-0.06394834]
 [-0.05132188]
 [-0.10641922]]
w_1gred:[[1.8664613]
 [2.1126423]]
b521_gred:-0.030243635177612305
b:[-3.3466394]
hypothesis: [[0.03400538]
 [0.22574684]
 [0.18540052]
 [0.6533905 ]]
cost: [[-0.00864926]
 [-0.06396411]
 [-0.05126467]
 [-0.10639507]]
w_0gred:[[1.8664613]
 [2.1141546]]
b522_gred:-0.

b598_gred:-0.03727101534605026
b:[-3.5299547]
hypothesis: [[0.02847184]
 [0.2135774 ]
 [0.18029954]
 [0.6708739 ]]
cost: [[-0.00722125]
 [-0.06006524]
 [-0.04970407]
 [-0.09979353]]
w_1gred:[[2.0156353]
 [2.2264597]]
b598_gred:-0.028887178748846054
b:[-3.53112]
hypothesis: [[0.02843962]
 [0.21362427]
 [0.18012737]
 [0.6709355 ]]
cost: [[-0.00721297]
 [-0.06008013]
 [-0.04965157]
 [-0.09977056]]
w_0gred:[[2.0156353]
 [2.227904 ]]
b599_gred:-0.03723428025841713
b:[-3.5322843]
hypothesis: [[0.02840747]
 [0.21342878]
 [0.18023041]
 [0.67108953]]
cost: [[-0.00720469]
 [-0.06001801]
 [-0.04968298]
 [-0.09971318]]
w_1gred:[[2.017497]
 [2.227904]]
b599_gred:-0.028870422393083572
b:[-3.5334487]
hypothesis: [[0.02837535]
 [0.21347564]
 [0.18005843]
 [0.67115116]]
cost: [[-0.00719642]
 [-0.0600329 ]
 [-0.04963055]
 [-0.09969022]]
w_0gred:[[2.017497 ]
 [2.2293477]]
b600_gred:-0.037197601050138474
b:[-3.534612]
hypothesis: [[0.0283433 ]
 [0.2132804 ]
 [0.18016131]
 [0.6713049 ]]
cost: [[-0.00718819

 [0.68671834]]
cost: [[-0.00607117]
 [-0.05665339]
 [-0.04803786]
 [-0.09395776]]
w_0gred:[[2.153885 ]
 [2.3366792]]
b676_gred:-0.034615885466337204
b:[-3.7068462]
hypothesis: [[0.02396635]
 [0.20259286]
 [0.1749086 ]
 [0.6868532 ]]
cost: [[-0.00606456]
 [-0.05659747]
 [-0.04806527]
 [-0.09390868]]
w_1gred:[[2.1556156]
 [2.3366792]]
b676_gred:-0.027638491243124008
b:[-3.7079504]
hypothesis: [[0.02394054]
 [0.20263775]
 [0.17474931]
 [0.6869129 ]]
cost: [[-0.00605795]
 [-0.05661154]
 [-0.04801702]
 [-0.09388695]]
w_0gred:[[2.1556156]
 [2.338061 ]]
b677_gred:-0.034584447741508484
b:[-3.7090533]
hypothesis: [[0.02391478]
 [0.20245959]
 [0.17483966]
 [0.6870477 ]]
cost: [[-0.00605134]
 [-0.05655569]
 [-0.04804439]
 [-0.09383788]]
w_1gred:[[2.1573448]
 [2.338061 ]]
b677_gred:-0.027623172849416733
b:[-3.7101564]
hypothesis: [[0.02388904]
 [0.20250449]
 [0.17468055]
 [0.68710744]]
cost: [[-0.00604476]
 [-0.05656978]
 [-0.04799618]
 [-0.09381615]]
w_0gred:[[2.1573448]
 [2.3394423]]
b678_gred:-

 [-0.08880737]]
w_0gred:[[2.2827625]
 [2.4409096]]
b753_gred:-0.032358139753341675
b:[-3.8725972]
hypothesis: [[0.02038027]
 [0.19283587]
 [0.16963492]
 [0.70113176]]
cost: [[-0.0051477 ]
 [-0.05355706]
 [-0.04647246]
 [-0.08876486]]
w_1gred:[[2.2843804]
 [2.4409096]]
b753_gred:-0.026508092880249023
b:[-3.873647]
hypothesis: [[0.02035932]
 [0.19287877]
 [0.16948712]
 [0.70118946]]
cost: [[-0.00514236]
 [-0.05357035]
 [-0.04642796]
 [-0.08874429]]
w_0gred:[[2.2843804]
 [2.442235 ]]
b754_gred:-0.03233085572719574
b:[-3.874696]
hypothesis: [[0.02033841]
 [0.19271551]
 [0.169567  ]
 [0.70130837]]
cost: [[-0.00513702]
 [-0.05351979]
 [-0.046452  ]
 [-0.0887019 ]]
w_1gred:[[2.285997]
 [2.442235]]
b754_gred:-0.02649402990937233
b:[-3.875745]
hypothesis: [[0.02031752]
 [0.1927584 ]
 [0.16941933]
 [0.7013661 ]]
cost: [[-0.00513168]
 [-0.05353306]
 [-0.04640756]
 [-0.08868131]]
w_0gred:[[2.285997 ]
 [2.4435596]]
b755_gred:-0.03230363503098488
b:[-3.8767934]
hypothesis: [[0.02029666]
 [0.19259532

 [0.71484065]]
cost: [[-0.00436364]
 [-0.05071485]
 [-0.04480043]
 [-0.08392391]]
w_0gred:[[2.41111 ]
 [2.547316]]
b835_gred:-0.030274145305156708
b:[-4.040412]
hypothesis: [[0.01728616]
 [0.18345751]
 [0.16413356]
 [0.7149459 ]]
cost: [[-0.00435933]
 [-0.05066908]
 [-0.04482161]
 [-0.0838871 ]]
w_1gred:[[2.4126236]
 [2.547316 ]]
b835_gred:-0.025399144738912582
b:[-4.04141]
hypothesis: [[0.01726921]
 [0.18349826]
 [0.1639967 ]
 [0.71500134]]
cost: [[-0.00435501]
 [-0.05068156]
 [-0.04478068]
 [-0.08386771]]
w_0gred:[[2.4126236]
 [2.5485861]]
b836_gred:-0.030250489711761475
b:[-4.042407]
hypothesis: [[0.0172523 ]
 [0.18334892]
 [0.16406737]
 [0.71510637]]
cost: [[-0.00435072]
 [-0.05063583]
 [-0.04480182]
 [-0.083831  ]]
w_1gred:[[2.4141362]
 [2.5485861]]
b836_gred:-0.025386177003383636
b:[-4.043404]
hypothesis: [[0.0172354 ]
 [0.1833897 ]
 [0.16393067]
 [0.71516186]]
cost: [[-0.00434641]
 [-0.05064831]
 [-0.04476093]
 [-0.0838116 ]]
w_0gred:[[2.4141362]
 [2.5498555]]
b837_gred:-0.03022

 [-0.07981078]]
w_0gred:[[2.5243447]
 [2.6432476]]
b912_gred:-0.02856263518333435
b:[-4.1906075]
hypothesis: [[0.01491137]
 [0.17546791]
 [0.15911406]
 [0.7267932 ]]
cost: [[-0.00375591]
 [-0.04823481]
 [-0.04332481]
 [-0.07977831]]
w_1gred:[[2.5257728]
 [2.6432476]]
b912_gred:-0.024434715509414673
b:[-4.191561]
hypothesis: [[0.01489737]
 [0.17550668]
 [0.15898651]
 [0.7268464 ]]
cost: [[-0.00375236]
 [-0.04824657]
 [-0.04328689]
 [-0.07976003]]
w_0gred:[[2.5257728]
 [2.6444693]]
b913_gred:-0.028541773557662964
b:[-4.1925144]
hypothesis: [[0.01488339]
 [0.17536879]
 [0.15904988]
 [0.72694045]]
cost: [[-0.00374882]
 [-0.04820475]
 [-0.04330573]
 [-0.07972768]]
w_1gred:[[2.5272   ]
 [2.6444693]]
b913_gred:-0.024422690272331238
b:[-4.1934676]
hypothesis: [[0.01486942]
 [0.17540754]
 [0.15892243]
 [0.7269937 ]]
cost: [[-0.00374526]
 [-0.0482165 ]
 [-0.04326785]
 [-0.07970937]]
w_0gred:[[2.5272   ]
 [2.6456904]]
b914_gred:-0.028520971536636353
b:[-4.19442]
hypothesis: [[0.01485548]
 [0.1752

 [2.7438197]]
b996_gred:-0.02691785618662834
b:[-4.3470616]
hypothesis: [[0.01277937]
 [0.167529  ]
 [0.15382703]
 [0.73864245]]
cost: [[-0.00321543]
 [-0.04583922]
 [-0.04175787]
 [-0.07573532]]
w_1gred:[[2.6421666]
 [2.7438197]]
b996_gred:-0.023457136005163193
b:[-4.3479714]
hypothesis: [[0.01276789]
 [0.16756567]
 [0.15370864]
 [0.73869324]]
cost: [[-0.00321253]
 [-0.04585025]
 [-0.04172289]
 [-0.07571813]]
w_0gred:[[2.6421666]
 [2.7449925]]
b997_gred:-0.026899531483650208
b:[-4.348881]
hypothesis: [[0.01275644]
 [0.16743888]
 [0.1537653 ]
 [0.7387773 ]]
cost: [[-0.00320963]
 [-0.04581216]
 [-0.04173964]
 [-0.0756897 ]]
w_1gred:[[2.6435115]
 [2.7449925]]
b997_gred:-0.023445960134267807
b:[-4.34979]
hypothesis: [[0.01274499]
 [0.16747554]
 [0.15364704]
 [0.738828  ]]
cost: [[-0.00320672]
 [-0.04582316]
 [-0.04170471]
 [-0.07567253]]
w_0gred:[[2.6435115]
 [2.7461648]]
b998_gred:-0.02688124030828476
b:[-4.350699]
hypothesis: [[0.01273356]
 [0.16734886]
 [0.15370362]
 [0.738912  ]]
cost

In [74]:
w


array([[2.6461987],
       [2.7485077]], dtype=float32)

In [75]:
b

array([-4.3534245], dtype=float32)

In [76]:
np.dot(X,w)+b

array([[-4.3534245],
       [-1.6049168],
       [-1.7072258],
       [ 1.0412822]], dtype=float32)

In [77]:
predict = sigmoid(np.dot(X,w)+b)
predict

array([[0.01269934],
       [0.16729555],
       [0.15352389],
       [0.7390973 ]], dtype=float32)

In [78]:
predict01 = tf.cast(predict >0.5, dtype =tf.float32)
print("===================================")
print("predict01")
print(predict01)

predict01
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [1.]], shape=(4, 1), dtype=float32)


In [79]:
ac01 = tf.equal(predict01,y )
ac01

<tf.Tensor: id=4, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [80]:
ac02 = tf.cast(ac01, dtype ="float32")
ac02

<tf.Tensor: id=6, shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [81]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=9, shape=(), dtype=float32, numpy=1.0>

In [82]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype = tf.float32))
print("========================================")
print("accuracy")
print(accuracy.numpy())

accuracy
1.0


In [83]:
arr = np.array([[0,1]], dtype = "float32")

predict = sigmoid(np.dot(arr,w)+b)
predict

array([[0.16729555]], dtype=float32)

In [84]:
predict = tf.cast(predict>0.5 , dtype = tf.float32)
predict.numpy()

array([[0.]], dtype=float32)

In [85]:
arr = np.array([[1,1]], dtype = "float32")
predict = sigmoid(np.dot(arr, w)+b)
predict

array([[0.7390973]], dtype=float32)

In [86]:
predict = tf.cast(predict>0.5 , dtype = tf.float32)
predict.numpy()

array([[1.]], dtype=float32)