In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from keras.layers import Dense
from keras.models import Sequential
from keras.optimizers import Adam
import numpy as np

Using TensorFlow backend.


In [2]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
X=data.data
y=data.target

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [5]:
model = Sequential()

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
scaler = StandardScaler()

In [8]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
X_train=scaler.transform(X_train)
X_train

array([[-0.7554853 , -0.18196246, -0.77661443, ..., -0.76316042,
        -0.28057239, -1.05166326],
       [ 1.51829451,  0.46550759,  1.50041814, ...,  1.9208086 ,
         1.13458084,  0.21447844],
       [-0.68885439, -1.20635259, -0.73807509, ..., -0.49923781,
         0.30461697, -0.93960052],
       ...,
       [-0.88319454, -0.55657014, -0.87135697, ..., -0.6290829 ,
         0.13765159, -0.27447192],
       [-0.12526794, -1.37978206, -0.1832692 , ..., -0.87531998,
        -0.14602747, -0.88050276],
       [-0.63610492,  0.5302546 , -0.64614271, ..., -0.65689605,
        -0.77012139,  0.09349528]])

In [10]:
model.add(Dense(30,input_dim=30,activation='sigmoid'))

In [11]:
model.add(Dense(10, activation='sigmoid'))

In [12]:
model.add(Dense(1,activation='sigmoid'))

In [13]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 30)                930       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                310       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 1,251
Trainable params: 1,251
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(loss='binary_crossentropy',optimizer=Adam(lr=0.0001), metrics=['acc'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [15]:
model.fit(X_train,y_train,epochs=1000)




Epoch 1/1000





455/455 [==============================] - 0s 890us/step - loss: 0.6602 - acc: 0.7648
Epoch 2/1000
455/455 [==============================] - 0s 57us/step - loss: 0.6552 - acc: 0.7670
Epoch 3/1000
455/455 [==============================] - 0s 55us/step - loss: 0.6503 - acc: 0.7692
Epoch 4/1000
455/455 [==============================] - 0s 50us/step - loss: 0.6455 - acc: 0.7692
Epoch 5/1000
455/455 [==============================] - 0s 42us/step - loss: 0.6407 - acc: 0.7582
Epoch 6/1000
455/455 [==============================] - 0s 55us/step - loss: 0.6361 - acc: 0.7670
Epoch 7/1000
455/455 [==============================] - 0s 53us/step - loss: 0.6316 - acc: 0.7670
Epoch 8/1000
455/455 [==============================] - 0s 61us/step - loss: 0.6271 - acc: 0.7604
Epoch 9/1000
455/455 [==============================] - 0s 50us/step - loss: 0.6226 - acc: 0.7604
Epoch 10/1000
455/455 [==============================] - 0s 55us/step - loss: 0.6184 - acc: 0.7604
Epoch 11/1

455/455 [==============================] - 0s 46us/step - loss: 0.3971 - acc: 0.9121
Epoch 68/1000
455/455 [==============================] - 0s 55us/step - loss: 0.3937 - acc: 0.9121
Epoch 69/1000
455/455 [==============================] - 0s 48us/step - loss: 0.3905 - acc: 0.9165
Epoch 70/1000
455/455 [==============================] - ETA: 0s - loss: 0.3532 - acc: 0.937 - 0s 44us/step - loss: 0.3872 - acc: 0.9187
Epoch 71/1000
455/455 [==============================] - 0s 44us/step - loss: 0.3840 - acc: 0.9209
Epoch 72/1000
455/455 [==============================] - 0s 55us/step - loss: 0.3809 - acc: 0.9253
Epoch 73/1000
455/455 [==============================] - 0s 57us/step - loss: 0.3777 - acc: 0.9253
Epoch 74/1000
455/455 [==============================] - 0s 42us/step - loss: 0.3746 - acc: 0.9275
Epoch 75/1000
455/455 [==============================] - 0s 53us/step - loss: 0.3715 - acc: 0.9275
Epoch 76/1000
455/455 [==============================] - 0s 48us/step - loss: 0.3685 

455/455 [==============================] - 0s 46us/step - loss: 0.2112 - acc: 0.9714
Epoch 150/1000
455/455 [==============================] - 0s 44us/step - loss: 0.2098 - acc: 0.9714
Epoch 151/1000
455/455 [==============================] - 0s 57us/step - loss: 0.2083 - acc: 0.9736
Epoch 152/1000
455/455 [==============================] - 0s 55us/step - loss: 0.2068 - acc: 0.9736
Epoch 153/1000
455/455 [==============================] - 0s 50us/step - loss: 0.2053 - acc: 0.9736
Epoch 154/1000
455/455 [==============================] - 0s 48us/step - loss: 0.2039 - acc: 0.9736
Epoch 155/1000
455/455 [==============================] - 0s 46us/step - loss: 0.2025 - acc: 0.9736
Epoch 156/1000
455/455 [==============================] - 0s 44us/step - loss: 0.2010 - acc: 0.9736
Epoch 157/1000
455/455 [==============================] - 0s 42us/step - loss: 0.1996 - acc: 0.9736
Epoch 158/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1982 - acc: 0.9736
Epoch 159/1000


455/455 [==============================] - 0s 48us/step - loss: 0.1276 - acc: 0.9824
Epoch 231/1000
455/455 [==============================] - 0s 50us/step - loss: 0.1269 - acc: 0.9824
Epoch 232/1000
455/455 [==============================] - 0s 42us/step - loss: 0.1263 - acc: 0.9824
Epoch 233/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1257 - acc: 0.9824
Epoch 234/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1250 - acc: 0.9824
Epoch 235/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1244 - acc: 0.9846
Epoch 236/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1238 - acc: 0.9846
Epoch 237/1000
455/455 [==============================] - 0s 50us/step - loss: 0.1231 - acc: 0.9846
Epoch 238/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1225 - acc: 0.9846
Epoch 239/1000
455/455 [==============================] - 0s 50us/step - loss: 0.1219 - acc: 0.9846
Epoch 240/1000


455/455 [==============================] - 0s 50us/step - loss: 0.0889 - acc: 0.9846
Epoch 313/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0885 - acc: 0.9846
Epoch 314/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0882 - acc: 0.9846
Epoch 315/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0879 - acc: 0.9846
Epoch 316/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0876 - acc: 0.9846
Epoch 317/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0872 - acc: 0.9868
Epoch 318/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0869 - acc: 0.9868
Epoch 319/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0866 - acc: 0.9868
Epoch 320/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0863 - acc: 0.9868
Epoch 321/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0860 - acc: 0.9868
Epoch 322/1000


455/455 [==============================] - 0s 48us/step - loss: 0.0680 - acc: 0.9890
Epoch 395/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0679 - acc: 0.9890
Epoch 396/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0676 - acc: 0.9890
Epoch 397/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0674 - acc: 0.9890
Epoch 398/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0673 - acc: 0.9890
Epoch 399/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0671 - acc: 0.9890
Epoch 400/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0669 - acc: 0.9890
Epoch 401/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0667 - acc: 0.9890
Epoch 402/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0665 - acc: 0.9890
Epoch 403/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0663 - acc: 0.9890
Epoch 404/1000


455/455 [==============================] - 0s 44us/step - loss: 0.0550 - acc: 0.9890
Epoch 477/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0549 - acc: 0.9890
Epoch 478/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0548 - acc: 0.9890
Epoch 479/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0546 - acc: 0.9890
Epoch 480/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0545 - acc: 0.9890
Epoch 481/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0544 - acc: 0.9890
Epoch 482/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0543 - acc: 0.9890
Epoch 483/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0542 - acc: 0.9890
Epoch 484/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0540 - acc: 0.9890
Epoch 485/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0539 - acc: 0.9890
Epoch 486/1000


455/455 [==============================] - 0s 42us/step - loss: 0.0462 - acc: 0.9912
Epoch 559/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0461 - acc: 0.9912
Epoch 560/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0460 - acc: 0.9912
Epoch 561/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0459 - acc: 0.9912
Epoch 562/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0458 - acc: 0.9912
Epoch 563/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0458 - acc: 0.9912
Epoch 564/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0457 - acc: 0.9912
Epoch 565/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0456 - acc: 0.9912
Epoch 566/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0455 - acc: 0.9912
Epoch 567/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0454 - acc: 0.9912
Epoch 568/1000


455/455 [==============================] - 0s 53us/step - loss: 0.0400 - acc: 0.9912
Epoch 641/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0400 - acc: 0.9912
Epoch 642/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0399 - acc: 0.9912
Epoch 643/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0398 - acc: 0.9912
Epoch 644/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0398 - acc: 0.9912
Epoch 645/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0397 - acc: 0.9912
Epoch 646/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0397 - acc: 0.9912
Epoch 647/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0396 - acc: 0.9912
Epoch 648/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0395 - acc: 0.9912
Epoch 649/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0395 - acc: 0.9912
Epoch 650/1000


455/455 [==============================] - 0s 64us/step - loss: 0.0356 - acc: 0.9912
Epoch 723/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0355 - acc: 0.9912
Epoch 724/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0354 - acc: 0.9912
Epoch 725/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0354 - acc: 0.9912
Epoch 726/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0354 - acc: 0.9912
Epoch 727/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0353 - acc: 0.9912
Epoch 728/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0352 - acc: 0.9912
Epoch 729/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0352 - acc: 0.9912
Epoch 730/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0352 - acc: 0.9912
Epoch 731/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0351 - acc: 0.9912
Epoch 732/1000


455/455 [==============================] - 0s 50us/step - loss: 0.0322 - acc: 0.9912
Epoch 805/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0322 - acc: 0.9912
Epoch 806/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0322 - acc: 0.9912
Epoch 807/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0321 - acc: 0.9912
Epoch 808/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0321 - acc: 0.9912
Epoch 809/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0320 - acc: 0.9912
Epoch 810/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0320 - acc: 0.9912
Epoch 811/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0320 - acc: 0.9912
Epoch 812/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0319 - acc: 0.9912
Epoch 813/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0319 - acc: 0.9912
Epoch 814/1000


455/455 [==============================] - 0s 48us/step - loss: 0.0297 - acc: 0.9912
Epoch 887/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0296 - acc: 0.9912
Epoch 888/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0297 - acc: 0.9912
Epoch 889/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0296 - acc: 0.9912
Epoch 890/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0295 - acc: 0.9912
Epoch 891/1000
455/455 [==============================] - 0s 66us/step - loss: 0.0295 - acc: 0.9912
Epoch 892/1000
455/455 [==============================] - 0s 68us/step - loss: 0.0295 - acc: 0.9912
Epoch 893/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0294 - acc: 0.9912
Epoch 894/1000
455/455 [==============================] - 0s 61us/step - loss: 0.0294 - acc: 0.9912
Epoch 895/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0294 - acc: 0.9912
Epoch 896/1000


455/455 [==============================] - 0s 61us/step - loss: 0.0276 - acc: 0.9934
Epoch 968/1000
455/455 [==============================] - 0s 66us/step - loss: 0.0276 - acc: 0.9934
Epoch 969/1000
455/455 [==============================] - 0s 79us/step - loss: 0.0276 - acc: 0.9934
Epoch 970/1000
455/455 [==============================] - 0s 88us/step - loss: 0.0275 - acc: 0.9934
Epoch 971/1000
455/455 [==============================] - 0s 81us/step - loss: 0.0275 - acc: 0.9934
Epoch 972/1000
455/455 [==============================] - 0s 77us/step - loss: 0.0275 - acc: 0.9934
Epoch 973/1000
455/455 [==============================] - 0s 77us/step - loss: 0.0275 - acc: 0.9934
Epoch 974/1000
455/455 [==============================] - 0s 92us/step - loss: 0.0275 - acc: 0.9934
Epoch 975/1000
455/455 [==============================] - 0s 79us/step - loss: 0.0274 - acc: 0.9934
Epoch 976/1000
455/455 [==============================] - 0s 92us/step - loss: 0.0274 - acc: 0.9934
Epoch 977/1000


In [16]:
X_test=scaler.transform(X_test)
X_test

array([[ 0.50217313, -0.86180602,  0.52890565, ...,  1.24210726,
         0.17169307,  0.41853298],
       [ 0.41888449, -1.83994828,  0.40847022, ...,  0.44247918,
        -0.57721963, -0.1072141 ],
       [-0.0891762 , -0.60513039, -0.14673712, ..., -0.81183344,
        -0.3794548 , -0.37649919],
       ...,
       [ 1.33228322,  1.23784687,  1.17925698, ...,  1.20431765,
         1.69059178,  0.50996726],
       [ 0.85198541,  0.66899818,  0.87415389, ...,  0.55735959,
         0.24950219, -0.49580977],
       [-0.40289673,  2.35704511, -0.45264311, ..., -0.77011371,
        -0.82037311, -1.05333584]])

In [17]:
predict=model.predict(X_test)
predict

array([[0.00864959],
       [0.9415121 ],
       [0.99712443],
       [0.99744993],
       [0.9974792 ],
       [0.9970479 ],
       [0.99743867],
       [0.0069679 ],
       [0.99729013],
       [0.9971733 ],
       [0.04470178],
       [0.99237925],
       [0.00728932],
       [0.9971961 ],
       [0.996848  ],
       [0.9970895 ],
       [0.9975056 ],
       [0.9975005 ],
       [0.99728286],
       [0.9973798 ],
       [0.9974829 ],
       [0.9966889 ],
       [0.9968207 ],
       [0.99723935],
       [0.9973464 ],
       [0.98982775],
       [0.9973399 ],
       [0.99711686],
       [0.00789899],
       [0.00669712],
       [0.9973998 ],
       [0.997285  ],
       [0.00670773],
       [0.01097208],
       [0.99746233],
       [0.99672246],
       [0.9947963 ],
       [0.9959682 ],
       [0.995677  ],
       [0.99753153],
       [0.00739142],
       [0.99752456],
       [0.99698985],
       [0.00682616],
       [0.0066753 ],
       [0.9862599 ],
       [0.99411356],
       [0.006

In [18]:
predict=np.where(predict>0.5,1,0)
predict

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
    

In [19]:
predict = predict.flatten()
predict

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1])

In [20]:
acc = (predict == y_test)
acc

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [21]:
np.average(acc)

0.9473684210526315