In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [3]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = data.data
y = data.target

In [5]:
X = np.array(X,dtype="float32")
y = np.array(y,dtype="float32")
y.shape

(150,)

In [6]:
X.shape

(150, 4)

In [7]:
y= y.reshape(-1,1)

In [8]:
y.shape

(150, 1)

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
enc = OneHotEncoder()

In [12]:
enc.fit(y)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [13]:
y_train_onehot = enc.transform(y_train).toarray()
y_train_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0

In [14]:
y_train_onehot = np.array(y_train_onehot,dtype='float32')
y_train_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0

In [15]:
y_test_onehot = enc.transform(y_test).toarray()
y_test_onehot = np.array(y_test_onehot, dtype = 'float32')
y_test_onehot

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train

array([[-1.3619262 ,  0.25152177, -1.3140396 , -1.2390804 ],
       [ 0.6885015 , -0.46145287,  0.34579998,  0.17212416],
       [-1.1206992 , -0.22379485, -1.2587116 , -1.2390804 ],
       [-1.723766  , -0.46145287, -1.2587116 , -1.2390804 ],
       [ 1.0503412 ,  0.01386317,  1.0650636 ,  1.583329  ],
       [ 0.08543461, -0.22379485,  0.7884237 ,  0.8135809 ],
       [-1.8443793 , -0.22379485, -1.4246955 , -1.3673718 ],
       [-1.0000858 ,  0.72683835, -1.2033836 , -1.2390804 ],
       [ 2.256475  ,  1.6774709 ,  1.6736714 ,  1.3267462 ],
       [ 0.6885015 , -0.9367695 ,  0.8990798 ,  0.94187224],
       [-1.1206992 ,  0.01386317, -1.2033836 , -1.2390804 ],
       [-0.03517865, -0.9367695 ,  0.7884237 ,  0.94187224],
       [ 0.92972803, -0.46145287,  0.5117838 ,  0.17212416],
       [-1.0000858 ,  0.9644964 , -1.3140396 , -1.1107891 ],
       [-1.4825395 ,  1.2021543 , -1.4800235 , -1.2390804 ],
       [-0.03517865, -0.9367695 ,  0.23514387, -0.2127498 ],
       [-0.75885934,  0.

In [17]:
initializer = tf.contrib.layers.xavier_initializer()

w0 = tf.Variable(initializer([4,16]))
w0

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



<tf.Variable 'Variable:0' shape=(4, 16) dtype=float32, numpy=
array([[-1.2323177e-01, -4.0629947e-01,  5.9150398e-02, -4.6071583e-01,
         1.0844892e-01,  5.1560104e-01,  2.6603168e-01, -2.9558462e-01,
        -2.9482040e-01,  9.0767264e-02,  4.8199177e-01,  2.9873317e-01,
         6.1331391e-03, -5.0856197e-01,  3.8160920e-01,  1.6283381e-01],
       [-4.1800737e-02,  1.7177325e-01, -4.8201355e-01,  3.6156577e-01,
        -4.5493174e-01, -4.2590269e-01, -4.4696552e-01,  3.6562127e-01,
        -4.8038188e-01, -3.5512665e-01, -2.6538473e-01,  4.8760927e-01,
         1.2279695e-01, -2.7358600e-01, -1.0045397e-01,  9.6620202e-02],
       [-3.3706591e-01, -3.0573410e-01, -3.3460957e-01, -1.8436608e-01,
        -3.4626514e-01, -1.6737002e-01, -2.6198491e-01, -5.1131696e-01,
         7.7345371e-02, -3.6907846e-01, -1.4943177e-01,  2.3049116e-04,
         2.2398055e-02,  4.7514391e-01, -1.7299375e-01, -4.1595811e-01],
       [-5.4053187e-02,  1.1820352e-01, -5.2034974e-02, -5.0790656e-01,

In [18]:
b0 = tf.Variable(initializer([16]))

In [19]:
w1 = tf.Variable(initializer([16,3]))

In [20]:
b1 = tf.Variable(initializer([3]))

In [21]:
tf.matmul(X_train, w0) + b0

<tf.Tensor: id=59, shape=(120, 16), dtype=float32, numpy=
array([[ 0.7818897 ,  1.1974641 ,  0.37022233, ..., -0.6693591 ,
         0.44493797,  0.7632098 ],
       [-0.07674068, -0.09875378,  0.20633921, ...,  0.00754204,
         0.3881049 ,  0.16478106],
       [ 0.7533823 ,  1.0008913 ,  0.5950868 , ..., -0.63570917,
         0.5751685 ,  0.73355037],
       ...,
       [-0.27725515, -0.32281265, -0.17524692, ..., -0.38349473,
         0.49765447,  0.24372508],
       [ 0.669055  ,  1.0171694 ,  0.15827167, ..., -1.0798072 ,
         0.617755  ,  0.8843205 ],
       [-0.53372955, -0.29130992, -0.4717556 , ...,  0.65678835,
        -0.21961752, -0.21326664]], dtype=float32)>

In [22]:
optimizer = tf.train.AdamOptimizer(0.1)

In [23]:
for step in range(1001):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
        hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
        cost = -tf.reduce_sum(y_train_onehot * tf.log(hypothesis1)) / len(hypothesis1)
    grads = tape.gradient(cost, [w0,w1,b0,b1])
    optimizer.apply_gradients(grads_and_vars = zip(grads, [w0,w1,b0,b1]))
    if step % 100 == 0:
        print(f"step: {step}, cost : {cost.numpy()}")

step: 0, cost : 1.1928013563156128
step: 100, cost : 0.02120119333267212
step: 200, cost : 0.006917736027389765
step: 300, cost : 0.0031464858911931515
step: 400, cost : 0.0017800008645281196
step: 500, cost : 0.001144524198025465
step: 600, cost : 0.0007978069479577243
step: 700, cost : 0.0005875738570466638
step: 800, cost : 0.00045030901674181223
step: 900, cost : 0.0003556244191713631
step: 1000, cost : 0.0002875336795113981


In [24]:
X_test =scaler.transform(X_test)
X_test

array([[ 1.2915684 ,  0.01386317,  0.7884237 ,  1.4550375 ],
       [-0.15579249, -1.4120861 ,  0.73309577,  1.0701636 ],
       [ 0.5678882 , -1.4120861 ,  0.6777678 ,  0.42870688],
       [ 0.5678882 , -0.46145287,  1.0650636 ,  0.8135809 ],
       [-0.27640575, -0.9367695 ,  0.2904718 ,  0.17212416],
       [-0.397019  ,  2.6281037 , -1.2587116 , -1.2390804 ],
       [-1.1206992 , -1.6497442 , -0.20747994, -0.2127498 ],
       [ 0.6885015 ,  0.25152177,  0.45645583,  0.42870688],
       [ 0.32666114, -0.69911146,  0.56711173,  0.04383295],
       [ 0.20604786, -0.9367695 ,  0.7884237 ,  0.55699825],
       [-0.397019  , -1.8874028 ,  0.17981595,  0.17212416],
       [ 2.4977021 ,  1.6774709 ,  1.5076876 ,  1.0701636 ],
       [ 0.32666114, -0.46145287,  0.56711173,  0.30041552],
       [-1.6031528 , -1.8874028 , -1.3140396 , -1.1107891 ],
       [ 0.5678882 , -1.8874028 ,  0.4011279 ,  0.17212416],
       [ 1.1709551 , -0.69911146,  0.6224399 ,  0.30041552],
       [-1.723766  ,  0.

In [25]:
hypothesis0 = tf. sigmoid(tf.matmul(X_test, w0) + b0)

In [26]:
predict = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
predict

<tf.Tensor: id=82239, shape=(30, 3), dtype=float32, numpy=
array([[7.37929113e-08, 4.77034191e-04, 9.99522924e-01],
       [4.13483137e-12, 1.06613189e-08, 1.00000000e+00],
       [5.02563444e-06, 1.71072304e-01, 8.28922689e-01],
       [5.70601812e-12, 1.36149580e-08, 1.00000000e+00],
       [1.74968554e-05, 9.99978900e-01, 3.58570560e-06],
       [9.99968171e-01, 3.18496568e-05, 4.62665018e-21],
       [8.33971208e-05, 9.99916553e-01, 2.37304421e-09],
       [1.34780885e-05, 9.99986529e-01, 8.26566073e-12],
       [1.11987711e-05, 9.99974608e-01, 1.41784749e-05],
       [6.20774265e-10, 3.17651006e-06, 9.99996781e-01],
       [6.71222642e-06, 9.99968767e-01, 2.45202009e-05],
       [3.43143802e-06, 1.94572769e-02, 9.80539322e-01],
       [1.94930381e-05, 9.99797881e-01, 1.82569202e-04],
       [9.99249518e-01, 7.50466250e-04, 1.67097776e-16],
       [4.25857115e-06, 9.99981165e-01, 1.45141385e-05],
       [4.40972508e-06, 9.99991655e-01, 3.97129497e-06],
       [9.99966145e-01, 3.383

In [27]:
predict01 = tf.argmax(predict,1)
predict01

<tf.Tensor: id=82241, shape=(30,), dtype=int64, numpy=
array([2, 2, 2, 2, 1, 0, 1, 1, 1, 2, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1,
       2, 0, 2, 2, 0, 1, 1, 2], dtype=int64)>

In [28]:
target = tf.argmax(y_test_onehot, 1)
target

<tf.Tensor: id=82244, shape=(30,), dtype=int64, numpy=
array([2, 2, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1,
       2, 0, 2, 2, 0, 1, 1, 2], dtype=int64)>

In [29]:
acc = tf.reduce_mean(tf.cast(tf.equal(predict01, target), dtype = tf.float32))
acc.numpy()

0.93333334