In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

Using TensorFlow backend.


In [2]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
X = data.data

In [4]:
y = data.target

In [5]:
y = y.reshape(-1, 1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [7]:
X_train.shape

(120, 4)

In [8]:
y_train.shape

(120, 1)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
X_train = scaler.transform(X_train)
X_train

array([[-0.9686654 ,  1.18687456, -1.29376574, -1.28218823],
       [ 0.38439103, -0.59901819,  0.56790298,  0.02839599],
       [-0.47664488, -0.15254501,  0.45507458,  0.42157126],
       [-0.59965001,  1.41011115, -1.23735154, -1.28218823],
       [-0.23063462, -0.3757816 , -0.05265326,  0.15945441],
       [-0.9686654 , -1.71520116, -0.22189587, -0.23372085],
       [-0.84566027,  1.63334775, -1.18093733, -1.28218823],
       [-1.33768079,  0.29392818, -1.35017994, -1.28218823],
       [-0.47664488,  1.85658434, -1.35017994, -1.02007139],
       [-0.10762949, -0.15254501,  0.28583197,  0.02839599],
       [ 0.01537564, -0.82225479,  0.22941776, -0.23372085],
       [ 0.38439103, -0.59901819,  0.17300356,  0.15945441],
       [-0.9686654 , -0.15254501, -1.18093733, -1.28218823],
       [ 0.50739616, -1.93843776,  0.45507458,  0.42157126],
       [-1.09167053, -0.15254501, -1.29376574, -1.28218823],
       [ 0.2613859 , -0.3757816 ,  0.45507458,  0.42157126],
       [ 0.63040129, -0.

In [11]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(categories = 'auto')
enc.fit(y)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [12]:
y_train_onehot = enc.transform(y_train).toarray()
y_train_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0

In [13]:
y_train_onehot = np.array(y_train_onehot, dtype='float32')

In [14]:
y_train_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0

In [15]:
y_test_onehot = enc.transform(y_test).toarray()
y_test_onehot = np.array(y_test_onehot, dtype='float32')

In [16]:
model = Sequential()

model.add(Dense(16, input_dim = 4, activation = 'sigmoid'))
model.add(Dense(3,activation = 'softmax'))

In [17]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=0.1),metrics=['acc'])

In [19]:
model.fit(X_train, y_train_onehot, epochs = 1000)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/1000





120/120 [==============================] - 0s 2ms/step - loss: 0.9489 - acc: 0.4583
Epoch 2/1000
120/120 [==============================] - 0s 50us/step - loss: 0.4864 - acc: 0.7833
Epoch 3/1000
120/120 [==============================] - 0s 58us/step - loss: 0.3731 - acc: 0.8417
Epoch 4/1000
120/120 [==============================] - 0s 58us/step - loss: 0.2696 - acc: 0.8917
Epoch 5/1000
120/120 [==============================] - 0s 75us/step - loss: 0.2475 - acc: 0.8917
Epoch 6/1000
120/120 [==============================] - 0s 50us/step - loss: 0.1924 - acc: 0.9167
Epoch 7/1000
120/120 [==============================] - 0s 66us/step - loss: 0.1758 - acc: 0.9167
Epoch 8/1000
120/120 [==============================] - 0s 66us/step - loss: 0.1349 - acc: 0.9583
Epoch 9/1000
120/120 [==============================] - 0s 50us/step - loss: 0.1189 - acc: 0.9500
Epoch 10/1000
120

In [20]:
X_test = scaler.transform(X_test)

In [21]:
pred = model.predict(X_test)

In [22]:
np.where(pred>0.5, 1, 0)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [23]:
predict = np.argmax(pred,1)

In [24]:
target = np.argmax(y_test_onehot, 1)

In [25]:
predict02 = (predict == target)

In [26]:
np.sum(predict02)/len(predict02)

0.9666666666666667